// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fivetran

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
	"github.com/ryan-pip/pulumi-fivetran/sdk/go/fivetran/internal"
)

// -This resource allows you to manage connectors schedule: pause/unpause connector, set dailySyncTime and sync_frequency.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/ryan-pip/pulumi-fivetran/sdk/go/fivetran"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := fivetran.NewFivetranConnectorSchedule(ctx, "myConnectorSchedule", &fivetran.FivetranConnectorScheduleArgs{
//				ConnectorId:     pulumi.Any(fivetran_connector.My_connector.Id),
//				SyncFrequency:   pulumi.String("1440"),
//				DailySyncTime:   pulumi.String("03:00"),
//				Paused:          pulumi.String("false"),
//				PauseAfterTrial: pulumi.String("true"),
//				ScheduleType:    pulumi.String("auto"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// You don't need to import this resource as it is synthetic.
//
// To fetch schedule values from existing connector use `fivetran_connector` data sourcehcl data "fivetran_connector" "my_connector" {
//
//	id = "my_connector_id" } now you can use schedule values from this data_source:
//
//	sync_frequency = data.fivetran_connector.my_connector.sync_frequency
//
//	paused = data.fivetran_connector.my_connector.paused This resource manages settings for already existing connector instance and doesn't create a new one. If you already have an existing connector with id = `my_connector_id` just define `fivetran_connector_schedule` resourcehcl resource "fivetran_connector_schedule" "my_connector_schedule" {
//
//	connector_id = "my_connector_id"
//
//	sync_frequency
//
//	= "360"
//
//	paused
//
//	= false
//
//	pause_after_trial
//
// = true
//
//	schedule_type
//
// = "auto" } -> NOTEYou can't have several resources managing the same `connector_id`. They will be in conflict ater each `apply`.
type FivetranConnectorSchedule struct {
	pulumi.CustomResourceState

	// The unique identifier for the connector
	ConnectorId pulumi.StringOutput `pulumi:"connectorId"`
	// The optional parameter that defines the sync start time when the sync frequency is already set or being set by the current request to 1440. It can be specified in one hour increments starting from 00:00 to 23:00. If not specified, we will use [the baseline sync start time](https://fivetran.com/docs/getting-started/syncoverview#syncfrequencyandscheduling). This parameter has no effect on the [0 to 60 minutes offset](https://fivetran.com/docs/getting-started/syncoverview#syncstarttimesandoffsets) used to determine the actual sync start time
	DailySyncTime pulumi.StringPtrOutput `pulumi:"dailySyncTime"`
	// Specifies whether the connector should be paused after the free trial period has ended
	PauseAfterTrial pulumi.StringOutput `pulumi:"pauseAfterTrial"`
	// Specifies whether the connector is paused
	Paused pulumi.StringOutput `pulumi:"paused"`
	// The connector schedule configuration type. Supported values: auto, manual
	ScheduleType pulumi.StringOutput `pulumi:"scheduleType"`
	// The connector sync frequency in minutes. Supported values: 5, 15, 30, 60, 120, 180, 360, 480, 720, 1440.
	SyncFrequency pulumi.StringOutput `pulumi:"syncFrequency"`
}

// NewFivetranConnectorSchedule registers a new resource with the given unique name, arguments, and options.
func NewFivetranConnectorSchedule(ctx *pulumi.Context,
	name string, args *FivetranConnectorScheduleArgs, opts ...pulumi.ResourceOption) (*FivetranConnectorSchedule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ConnectorId == nil {
		return nil, errors.New("invalid value for required argument 'ConnectorId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource FivetranConnectorSchedule
	err := ctx.RegisterResource("fivetran:index/fivetranConnectorSchedule:FivetranConnectorSchedule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFivetranConnectorSchedule gets an existing FivetranConnectorSchedule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFivetranConnectorSchedule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FivetranConnectorScheduleState, opts ...pulumi.ResourceOption) (*FivetranConnectorSchedule, error) {
	var resource FivetranConnectorSchedule
	err := ctx.ReadResource("fivetran:index/fivetranConnectorSchedule:FivetranConnectorSchedule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FivetranConnectorSchedule resources.
type fivetranConnectorScheduleState struct {
	// The unique identifier for the connector
	ConnectorId *string `pulumi:"connectorId"`
	// The optional parameter that defines the sync start time when the sync frequency is already set or being set by the current request to 1440. It can be specified in one hour increments starting from 00:00 to 23:00. If not specified, we will use [the baseline sync start time](https://fivetran.com/docs/getting-started/syncoverview#syncfrequencyandscheduling). This parameter has no effect on the [0 to 60 minutes offset](https://fivetran.com/docs/getting-started/syncoverview#syncstarttimesandoffsets) used to determine the actual sync start time
	DailySyncTime *string `pulumi:"dailySyncTime"`
	// Specifies whether the connector should be paused after the free trial period has ended
	PauseAfterTrial *string `pulumi:"pauseAfterTrial"`
	// Specifies whether the connector is paused
	Paused *string `pulumi:"paused"`
	// The connector schedule configuration type. Supported values: auto, manual
	ScheduleType *string `pulumi:"scheduleType"`
	// The connector sync frequency in minutes. Supported values: 5, 15, 30, 60, 120, 180, 360, 480, 720, 1440.
	SyncFrequency *string `pulumi:"syncFrequency"`
}

type FivetranConnectorScheduleState struct {
	// The unique identifier for the connector
	ConnectorId pulumi.StringPtrInput
	// The optional parameter that defines the sync start time when the sync frequency is already set or being set by the current request to 1440. It can be specified in one hour increments starting from 00:00 to 23:00. If not specified, we will use [the baseline sync start time](https://fivetran.com/docs/getting-started/syncoverview#syncfrequencyandscheduling). This parameter has no effect on the [0 to 60 minutes offset](https://fivetran.com/docs/getting-started/syncoverview#syncstarttimesandoffsets) used to determine the actual sync start time
	DailySyncTime pulumi.StringPtrInput
	// Specifies whether the connector should be paused after the free trial period has ended
	PauseAfterTrial pulumi.StringPtrInput
	// Specifies whether the connector is paused
	Paused pulumi.StringPtrInput
	// The connector schedule configuration type. Supported values: auto, manual
	ScheduleType pulumi.StringPtrInput
	// The connector sync frequency in minutes. Supported values: 5, 15, 30, 60, 120, 180, 360, 480, 720, 1440.
	SyncFrequency pulumi.StringPtrInput
}

func (FivetranConnectorScheduleState) ElementType() reflect.Type {
	return reflect.TypeOf((*fivetranConnectorScheduleState)(nil)).Elem()
}

type fivetranConnectorScheduleArgs struct {
	// The unique identifier for the connector
	ConnectorId string `pulumi:"connectorId"`
	// The optional parameter that defines the sync start time when the sync frequency is already set or being set by the current request to 1440. It can be specified in one hour increments starting from 00:00 to 23:00. If not specified, we will use [the baseline sync start time](https://fivetran.com/docs/getting-started/syncoverview#syncfrequencyandscheduling). This parameter has no effect on the [0 to 60 minutes offset](https://fivetran.com/docs/getting-started/syncoverview#syncstarttimesandoffsets) used to determine the actual sync start time
	DailySyncTime *string `pulumi:"dailySyncTime"`
	// Specifies whether the connector should be paused after the free trial period has ended
	PauseAfterTrial *string `pulumi:"pauseAfterTrial"`
	// Specifies whether the connector is paused
	Paused *string `pulumi:"paused"`
	// The connector schedule configuration type. Supported values: auto, manual
	ScheduleType *string `pulumi:"scheduleType"`
	// The connector sync frequency in minutes. Supported values: 5, 15, 30, 60, 120, 180, 360, 480, 720, 1440.
	SyncFrequency *string `pulumi:"syncFrequency"`
}

// The set of arguments for constructing a FivetranConnectorSchedule resource.
type FivetranConnectorScheduleArgs struct {
	// The unique identifier for the connector
	ConnectorId pulumi.StringInput
	// The optional parameter that defines the sync start time when the sync frequency is already set or being set by the current request to 1440. It can be specified in one hour increments starting from 00:00 to 23:00. If not specified, we will use [the baseline sync start time](https://fivetran.com/docs/getting-started/syncoverview#syncfrequencyandscheduling). This parameter has no effect on the [0 to 60 minutes offset](https://fivetran.com/docs/getting-started/syncoverview#syncstarttimesandoffsets) used to determine the actual sync start time
	DailySyncTime pulumi.StringPtrInput
	// Specifies whether the connector should be paused after the free trial period has ended
	PauseAfterTrial pulumi.StringPtrInput
	// Specifies whether the connector is paused
	Paused pulumi.StringPtrInput
	// The connector schedule configuration type. Supported values: auto, manual
	ScheduleType pulumi.StringPtrInput
	// The connector sync frequency in minutes. Supported values: 5, 15, 30, 60, 120, 180, 360, 480, 720, 1440.
	SyncFrequency pulumi.StringPtrInput
}

func (FivetranConnectorScheduleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*fivetranConnectorScheduleArgs)(nil)).Elem()
}

type FivetranConnectorScheduleInput interface {
	pulumi.Input

	ToFivetranConnectorScheduleOutput() FivetranConnectorScheduleOutput
	ToFivetranConnectorScheduleOutputWithContext(ctx context.Context) FivetranConnectorScheduleOutput
}

func (*FivetranConnectorSchedule) ElementType() reflect.Type {
	return reflect.TypeOf((**FivetranConnectorSchedule)(nil)).Elem()
}

func (i *FivetranConnectorSchedule) ToFivetranConnectorScheduleOutput() FivetranConnectorScheduleOutput {
	return i.ToFivetranConnectorScheduleOutputWithContext(context.Background())
}

func (i *FivetranConnectorSchedule) ToFivetranConnectorScheduleOutputWithContext(ctx context.Context) FivetranConnectorScheduleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FivetranConnectorScheduleOutput)
}

func (i *FivetranConnectorSchedule) ToOutput(ctx context.Context) pulumix.Output[*FivetranConnectorSchedule] {
	return pulumix.Output[*FivetranConnectorSchedule]{
		OutputState: i.ToFivetranConnectorScheduleOutputWithContext(ctx).OutputState,
	}
}

// FivetranConnectorScheduleArrayInput is an input type that accepts FivetranConnectorScheduleArray and FivetranConnectorScheduleArrayOutput values.
// You can construct a concrete instance of `FivetranConnectorScheduleArrayInput` via:
//
//	FivetranConnectorScheduleArray{ FivetranConnectorScheduleArgs{...} }
type FivetranConnectorScheduleArrayInput interface {
	pulumi.Input

	ToFivetranConnectorScheduleArrayOutput() FivetranConnectorScheduleArrayOutput
	ToFivetranConnectorScheduleArrayOutputWithContext(context.Context) FivetranConnectorScheduleArrayOutput
}

type FivetranConnectorScheduleArray []FivetranConnectorScheduleInput

func (FivetranConnectorScheduleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FivetranConnectorSchedule)(nil)).Elem()
}

func (i FivetranConnectorScheduleArray) ToFivetranConnectorScheduleArrayOutput() FivetranConnectorScheduleArrayOutput {
	return i.ToFivetranConnectorScheduleArrayOutputWithContext(context.Background())
}

func (i FivetranConnectorScheduleArray) ToFivetranConnectorScheduleArrayOutputWithContext(ctx context.Context) FivetranConnectorScheduleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FivetranConnectorScheduleArrayOutput)
}

func (i FivetranConnectorScheduleArray) ToOutput(ctx context.Context) pulumix.Output[[]*FivetranConnectorSchedule] {
	return pulumix.Output[[]*FivetranConnectorSchedule]{
		OutputState: i.ToFivetranConnectorScheduleArrayOutputWithContext(ctx).OutputState,
	}
}

// FivetranConnectorScheduleMapInput is an input type that accepts FivetranConnectorScheduleMap and FivetranConnectorScheduleMapOutput values.
// You can construct a concrete instance of `FivetranConnectorScheduleMapInput` via:
//
//	FivetranConnectorScheduleMap{ "key": FivetranConnectorScheduleArgs{...} }
type FivetranConnectorScheduleMapInput interface {
	pulumi.Input

	ToFivetranConnectorScheduleMapOutput() FivetranConnectorScheduleMapOutput
	ToFivetranConnectorScheduleMapOutputWithContext(context.Context) FivetranConnectorScheduleMapOutput
}

type FivetranConnectorScheduleMap map[string]FivetranConnectorScheduleInput

func (FivetranConnectorScheduleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FivetranConnectorSchedule)(nil)).Elem()
}

func (i FivetranConnectorScheduleMap) ToFivetranConnectorScheduleMapOutput() FivetranConnectorScheduleMapOutput {
	return i.ToFivetranConnectorScheduleMapOutputWithContext(context.Background())
}

func (i FivetranConnectorScheduleMap) ToFivetranConnectorScheduleMapOutputWithContext(ctx context.Context) FivetranConnectorScheduleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FivetranConnectorScheduleMapOutput)
}

func (i FivetranConnectorScheduleMap) ToOutput(ctx context.Context) pulumix.Output[map[string]*FivetranConnectorSchedule] {
	return pulumix.Output[map[string]*FivetranConnectorSchedule]{
		OutputState: i.ToFivetranConnectorScheduleMapOutputWithContext(ctx).OutputState,
	}
}

type FivetranConnectorScheduleOutput struct{ *pulumi.OutputState }

func (FivetranConnectorScheduleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FivetranConnectorSchedule)(nil)).Elem()
}

func (o FivetranConnectorScheduleOutput) ToFivetranConnectorScheduleOutput() FivetranConnectorScheduleOutput {
	return o
}

func (o FivetranConnectorScheduleOutput) ToFivetranConnectorScheduleOutputWithContext(ctx context.Context) FivetranConnectorScheduleOutput {
	return o
}

func (o FivetranConnectorScheduleOutput) ToOutput(ctx context.Context) pulumix.Output[*FivetranConnectorSchedule] {
	return pulumix.Output[*FivetranConnectorSchedule]{
		OutputState: o.OutputState,
	}
}

// The unique identifier for the connector
func (o FivetranConnectorScheduleOutput) ConnectorId() pulumi.StringOutput {
	return o.ApplyT(func(v *FivetranConnectorSchedule) pulumi.StringOutput { return v.ConnectorId }).(pulumi.StringOutput)
}

// The optional parameter that defines the sync start time when the sync frequency is already set or being set by the current request to 1440. It can be specified in one hour increments starting from 00:00 to 23:00. If not specified, we will use [the baseline sync start time](https://fivetran.com/docs/getting-started/syncoverview#syncfrequencyandscheduling). This parameter has no effect on the [0 to 60 minutes offset](https://fivetran.com/docs/getting-started/syncoverview#syncstarttimesandoffsets) used to determine the actual sync start time
func (o FivetranConnectorScheduleOutput) DailySyncTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *FivetranConnectorSchedule) pulumi.StringPtrOutput { return v.DailySyncTime }).(pulumi.StringPtrOutput)
}

// Specifies whether the connector should be paused after the free trial period has ended
func (o FivetranConnectorScheduleOutput) PauseAfterTrial() pulumi.StringOutput {
	return o.ApplyT(func(v *FivetranConnectorSchedule) pulumi.StringOutput { return v.PauseAfterTrial }).(pulumi.StringOutput)
}

// Specifies whether the connector is paused
func (o FivetranConnectorScheduleOutput) Paused() pulumi.StringOutput {
	return o.ApplyT(func(v *FivetranConnectorSchedule) pulumi.StringOutput { return v.Paused }).(pulumi.StringOutput)
}

// The connector schedule configuration type. Supported values: auto, manual
func (o FivetranConnectorScheduleOutput) ScheduleType() pulumi.StringOutput {
	return o.ApplyT(func(v *FivetranConnectorSchedule) pulumi.StringOutput { return v.ScheduleType }).(pulumi.StringOutput)
}

// The connector sync frequency in minutes. Supported values: 5, 15, 30, 60, 120, 180, 360, 480, 720, 1440.
func (o FivetranConnectorScheduleOutput) SyncFrequency() pulumi.StringOutput {
	return o.ApplyT(func(v *FivetranConnectorSchedule) pulumi.StringOutput { return v.SyncFrequency }).(pulumi.StringOutput)
}

type FivetranConnectorScheduleArrayOutput struct{ *pulumi.OutputState }

func (FivetranConnectorScheduleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*FivetranConnectorSchedule)(nil)).Elem()
}

func (o FivetranConnectorScheduleArrayOutput) ToFivetranConnectorScheduleArrayOutput() FivetranConnectorScheduleArrayOutput {
	return o
}

func (o FivetranConnectorScheduleArrayOutput) ToFivetranConnectorScheduleArrayOutputWithContext(ctx context.Context) FivetranConnectorScheduleArrayOutput {
	return o
}

func (o FivetranConnectorScheduleArrayOutput) ToOutput(ctx context.Context) pulumix.Output[[]*FivetranConnectorSchedule] {
	return pulumix.Output[[]*FivetranConnectorSchedule]{
		OutputState: o.OutputState,
	}
}

func (o FivetranConnectorScheduleArrayOutput) Index(i pulumi.IntInput) FivetranConnectorScheduleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *FivetranConnectorSchedule {
		return vs[0].([]*FivetranConnectorSchedule)[vs[1].(int)]
	}).(FivetranConnectorScheduleOutput)
}

type FivetranConnectorScheduleMapOutput struct{ *pulumi.OutputState }

func (FivetranConnectorScheduleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*FivetranConnectorSchedule)(nil)).Elem()
}

func (o FivetranConnectorScheduleMapOutput) ToFivetranConnectorScheduleMapOutput() FivetranConnectorScheduleMapOutput {
	return o
}

func (o FivetranConnectorScheduleMapOutput) ToFivetranConnectorScheduleMapOutputWithContext(ctx context.Context) FivetranConnectorScheduleMapOutput {
	return o
}

func (o FivetranConnectorScheduleMapOutput) ToOutput(ctx context.Context) pulumix.Output[map[string]*FivetranConnectorSchedule] {
	return pulumix.Output[map[string]*FivetranConnectorSchedule]{
		OutputState: o.OutputState,
	}
}

func (o FivetranConnectorScheduleMapOutput) MapIndex(k pulumi.StringInput) FivetranConnectorScheduleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *FivetranConnectorSchedule {
		return vs[0].(map[string]*FivetranConnectorSchedule)[vs[1].(string)]
	}).(FivetranConnectorScheduleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FivetranConnectorScheduleInput)(nil)).Elem(), &FivetranConnectorSchedule{})
	pulumi.RegisterInputType(reflect.TypeOf((*FivetranConnectorScheduleArrayInput)(nil)).Elem(), FivetranConnectorScheduleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FivetranConnectorScheduleMapInput)(nil)).Elem(), FivetranConnectorScheduleMap{})
	pulumi.RegisterOutputType(FivetranConnectorScheduleOutput{})
	pulumi.RegisterOutputType(FivetranConnectorScheduleArrayOutput{})
	pulumi.RegisterOutputType(FivetranConnectorScheduleMapOutput{})
}
