// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Outputs
{

    [OutputType]
    public sealed class ConnectorConfigReportFilter
    {
        public readonly string? Dimension;
        public readonly string? Expression;
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: The dimension name to filter on.
        /// </summary>
        public readonly string? FilterDimension;
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: Filter type for reports request. Possible values are INCLUDE and EXCLUDE
        /// </summary>
        public readonly string? FilterType;
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: The filter value.
        /// </summary>
        public readonly string? FilterValue;
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: The filter values for EXACT match type.
        /// </summary>
        public readonly ImmutableArray<string> FilterValues;
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: The filter match type.
        /// </summary>
        public readonly string? MatchType;

        [OutputConstructor]
        private ConnectorConfigReportFilter(
            string? dimension,

            string? expression,

            string? filterDimension,

            string? filterType,

            string? filterValue,

            ImmutableArray<string> filterValues,

            string? matchType)
        {
            Dimension = dimension;
            Expression = expression;
            FilterDimension = filterDimension;
            FilterType = filterType;
            FilterValue = filterValue;
            FilterValues = filterValues;
            MatchType = matchType;
        }
    }
}
