// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Outputs
{

    [OutputType]
    public sealed class ConnectorConfigCustomPayload
    {
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AwsLambda`: Payload Key
        /// 	- Service `AzureFunction`: Payload Key
        /// 	- Service `GoogleCloudFunction`: Payload Key
        /// </summary>
        public readonly string? Key;
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AwsLambda`: Payload Value
        /// 	- Service `AzureFunction`: Payload Value
        /// 	- Service `GoogleCloudFunction`: Payload Value
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private ConnectorConfigCustomPayload(
            string? key,

            string? value)
        {
            Key = key;
            Value = value;
        }
    }
}
