// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Outputs
{

    [OutputType]
    public sealed class ConnectorConfigAccountsRedditAd
    {
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `RedditAds`: Reddit username of the additional linked account.
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private ConnectorConfigAccountsRedditAd(string? name)
        {
            Name = name;
        }
    }
}
