// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Outputs
{

    [OutputType]
    public sealed class ConnectorConfigGcsCredentials
    {
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Amplitude`: Your GCS bucket name
        /// 	- Service `Pendo`: GCS bucket name
        /// </summary>
        public readonly string? BucketName;
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Amplitude`: Prefix to filter out the data
        /// 	- Service `Pendo`: GCS home folder
        /// </summary>
        public readonly string? HomeFolder;

        [OutputConstructor]
        private ConnectorConfigGcsCredentials(
            string? bucketName,

            string? homeFolder)
        {
            BucketName = bucketName;
            HomeFolder = homeFolder;
        }
    }
}
