// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Outputs
{

    [OutputType]
    public sealed class ConnectorScheduleSchedule
    {
        /// <summary>
        /// The cron expression for the sync schedule. Required for CRON schedule type.
        /// </summary>
        public readonly string? Cron;
        /// <summary>
        /// The days of the week to run the sync. Used with INTERVAL and TIME*OF*DAY schedule types. Supported values: MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY.
        /// </summary>
        public readonly ImmutableArray<string> DaysOfWeeks;
        /// <summary>
        /// The sync interval in minutes. Required for INTERVAL schedule type.
        /// </summary>
        public readonly int? Interval;
        /// <summary>
        /// The schedule type. Supported values: INTERVAL, TIME*OF*DAY, CRON, MANUAL.
        /// </summary>
        public readonly string? ScheduleType;
        /// <summary>
        /// The time of day to run the sync. Required for TIME*OF*DAY schedule type. Supported values: "00:00" to "23:00".
        /// </summary>
        public readonly string? TimeOfDay;

        [OutputConstructor]
        private ConnectorScheduleSchedule(
            string? cron,

            ImmutableArray<string> daysOfWeeks,

            int? interval,

            string? scheduleType,

            string? timeOfDay)
        {
            Cron = cron;
            DaysOfWeeks = daysOfWeeks;
            Interval = interval;
            ScheduleType = scheduleType;
            TimeOfDay = timeOfDay;
        }
    }
}
