// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Outputs
{

    [OutputType]
    public sealed class GetConnectorConfigFileResult
    {
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Email`: Only attachments from emails with this subject will be synced. Leave this field blank to sync all attachments.
        /// </summary>
        public readonly string EmailSubject;
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AzureBlobStorage`: All files in your search path matching this regular expression will be synced per table. We have discontinued this field, and will delete it by August 31, 2025.
        /// 	- Service `Email`: All files in your search path matching this regular expression will be synced per table.
        /// 	- Service `Gcs`: All files in your search path matching this regular expression will be synced per table.
        /// 	- Service `GoogleDrive`: All files in your search path matching this regular expression will be synced per table.
        /// 	- Service `S3`: All files in your search path matching this regular expression will be synced per table.
        /// 	- Service `S3CompatibleStorage`: All files in your search path matching this regular expression will be synced per table.
        /// 	- Service `Sftp`: All files in your search path matching this regular expression will be synced per table.
        /// 	- Service `SharePoint`: All files in your search path matching this regular expression will be synced per table.
        /// </summary>
        public readonly string FilePattern;
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AzureBlobStorage`: All files matching the above pattern will be synced to this table.
        /// 	- Service `Email`: All files matching the above pattern will be synced to this table.
        /// 	- Service `Gcs`: All files matching the above pattern will be synced to this table.
        /// 	- Service `GoogleDrive`: All files matching the above pattern will be synced to this table.
        /// 	- Service `S3`: All files matching the above pattern will be synced to this table.
        /// 	- Service `S3CompatibleStorage`: All files matching the above pattern will be synced to this table.
        /// 	- Service `Sftp`: All files matching the above pattern will be synced to this table.
        /// 	- Service `SharePoint`: All files matching the above pattern will be synced to this table.
        /// </summary>
        public readonly string TableName;

        [OutputConstructor]
        private GetConnectorConfigFileResult(
            string emailSubject,

            string filePattern,

            string tableName)
        {
            EmailSubject = emailSubject;
            FilePattern = filePattern;
            TableName = tableName;
        }
    }
}
