// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Outputs
{

    [OutputType]
    public sealed class GetConnectorConfigAzureCredentialsResult
    {
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Pendo`: Azure connection string
        /// </summary>
        public readonly string ConnectionString;
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Pendo`: Azure container name
        /// </summary>
        public readonly string ContainerName;
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Pendo`: Azure home folder
        /// </summary>
        public readonly string HomeFolder;

        [OutputConstructor]
        private GetConnectorConfigAzureCredentialsResult(
            string connectionString,

            string containerName,

            string homeFolder)
        {
            ConnectionString = connectionString;
            ContainerName = containerName;
            HomeFolder = homeFolder;
        }
    }
}
