// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Outputs
{

    [OutputType]
    public sealed class GetExternalLoggingConfigResult
    {
        public readonly string AccessKeyId;
        public readonly string AccessKeySecret;
        public readonly string ApiKey;
        public readonly string Channel;
        public readonly bool EnableSsl;
        public readonly string ExternalId;
        public readonly string Host;
        public readonly string Hostname;
        public readonly string LogGroupName;
        public readonly int Port;
        public readonly string PrimaryKey;
        public readonly string ProjectId;
        public readonly string Region;
        public readonly string RoleArn;
        public readonly string ServiceAccountKey;
        public readonly string SubDomain;
        public readonly string Token;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetExternalLoggingConfigResult(
            string accessKeyId,

            string accessKeySecret,

            string apiKey,

            string channel,

            bool enableSsl,

            string externalId,

            string host,

            string hostname,

            string logGroupName,

            int port,

            string primaryKey,

            string projectId,

            string region,

            string roleArn,

            string serviceAccountKey,

            string subDomain,

            string token,

            string workspaceId)
        {
            AccessKeyId = accessKeyId;
            AccessKeySecret = accessKeySecret;
            ApiKey = apiKey;
            Channel = channel;
            EnableSsl = enableSsl;
            ExternalId = externalId;
            Host = host;
            Hostname = hostname;
            LogGroupName = logGroupName;
            Port = port;
            PrimaryKey = primaryKey;
            ProjectId = projectId;
            Region = region;
            RoleArn = roleArn;
            ServiceAccountKey = serviceAccountKey;
            SubDomain = subDomain;
            Token = token;
            WorkspaceId = workspaceId;
        }
    }
}
