// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Outputs
{

    [OutputType]
    public sealed class GetQuickstartPackagesPackageConfigurableVariablesResult
    {
        /// <summary>
        /// List of allowed values for the variable, if restricted.
        /// </summary>
        public readonly ImmutableArray<string> AllowedValues;
        /// <summary>
        /// Human-readable description of the variable.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The variable type (e.g. STRING, INTEGER, BOOLEAN, DATE).
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetQuickstartPackagesPackageConfigurableVariablesResult(
            ImmutableArray<string> allowedValues,

            string description,

            string type)
        {
            AllowedValues = allowedValues;
            Description = description;
            Type = type;
        }
    }
}
