# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ConnectionV2Args', 'ConnectionV2']

@pulumi.input_type
class ConnectionV2Args:
    def __init__(__self__, *,
                 destination_schema_names: pulumi.Input[_builtins.str],
                 group_id: pulumi.Input[_builtins.str],
                 service: pulumi.Input[_builtins.str],
                 auth: Optional[Any] = None,
                 config: Optional[Any] = None,
                 connect_card_config: pulumi.Input[Optional['ConnectionV2ConnectCardConfigArgs']] = None,
                 daily_sync_time: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_sensitivity: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_threshold: pulumi.Input[Optional[_builtins.int]] = None,
                 destination_configuration: pulumi.Input[Optional['ConnectionV2DestinationConfigurationArgs']] = None,
                 hybrid_deployment_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 networking_method: pulumi.Input[Optional[_builtins.str]] = None,
                 pause_after_trial: pulumi.Input[Optional[_builtins.bool]] = None,
                 private_link_id: pulumi.Input[Optional[_builtins.str]] = None,
                 proxy_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 run_setup_tests: pulumi.Input[Optional[_builtins.bool]] = None,
                 schedule_type: pulumi.Input[Optional[_builtins.str]] = None,
                 sync_frequency: pulumi.Input[Optional[_builtins.int]] = None,
                 trust_certificates: pulumi.Input[Optional[_builtins.bool]] = None,
                 trust_fingerprints: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a ConnectionV2 resource.

        :param pulumi.Input[_builtins.str] destination_schema_names: Defines how schema names appear in the destination. Supported values: `FIVETRAN_NAMING`, `SOURCE_NAMING`. Changing this forces the connection to be replaced.
        :param pulumi.Input[_builtins.str] group_id: The unique identifier for the Group (Destination) within the Fivetran system. Changing this forces the connection to be replaced.
        :param pulumi.Input[_builtins.str] service: The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). Changing this forces the connection to be replaced.
        :param Any auth: Service-specific authorization configuration. The accepted fields are defined by connector metadata at runtime.
        :param Any config: Service-specific connection configuration. The accepted fields are defined by connector metadata at runtime.
        :param pulumi.Input['ConnectionV2ConnectCardConfigArgs'] connect_card_config: Configuration for the interactive Connect Card setup flow.
        :param pulumi.Input[_builtins.str] daily_sync_time: Sync start time. Only used when `sync_frequency` is `1440`.
        :param pulumi.Input[_builtins.str] data_delay_sensitivity: The level of data delay notification threshold. Possible values: `LOW`, `NORMAL`, `HIGH`, `CUSTOM`, `SYNC_FREQUENCY`.
        :param pulumi.Input[_builtins.int] data_delay_threshold: Custom sync delay notification threshold in minutes. Only used when `data_delay_sensitivity` is `CUSTOM`.
        :param pulumi.Input['ConnectionV2DestinationConfigurationArgs'] destination_configuration: Destination-specific configuration for the connection.
        :param pulumi.Input[_builtins.str] hybrid_deployment_agent_id: The hybrid deployment agent ID for the group the connection belongs to.
        :param pulumi.Input[_builtins.str] networking_method: The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        :param pulumi.Input[_builtins.bool] pause_after_trial: Whether the connection should be paused after the free trial period has ended.
        :param pulumi.Input[_builtins.str] private_link_id: The private link ID. Required when `networking_method` is `PrivateLink`.
        :param pulumi.Input[_builtins.str] proxy_agent_id: The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        :param pulumi.Input[_builtins.bool] run_setup_tests: Whether to run setup tests when creating or updating the connection.
        :param pulumi.Input[_builtins.str] schedule_type: The connection schedule configuration type. Supported values: `auto`, `manual`.
        :param pulumi.Input[_builtins.int] sync_frequency: The connection sync frequency in minutes.
        :param pulumi.Input[_builtins.bool] trust_certificates: Whether Fivetran should trust certificates automatically.
        :param pulumi.Input[_builtins.bool] trust_fingerprints: Whether Fivetran should trust SSH fingerprints automatically.
        """
        pulumi.set(__self__, "destination_schema_names", destination_schema_names)
        pulumi.set(__self__, "group_id", group_id)
        pulumi.set(__self__, "service", service)
        if auth is not None:
            pulumi.set(__self__, "auth", auth)
        if config is not None:
            pulumi.set(__self__, "config", config)
        if connect_card_config is not None:
            pulumi.set(__self__, "connect_card_config", connect_card_config)
        if daily_sync_time is not None:
            pulumi.set(__self__, "daily_sync_time", daily_sync_time)
        if data_delay_sensitivity is not None:
            pulumi.set(__self__, "data_delay_sensitivity", data_delay_sensitivity)
        if data_delay_threshold is not None:
            pulumi.set(__self__, "data_delay_threshold", data_delay_threshold)
        if destination_configuration is not None:
            pulumi.set(__self__, "destination_configuration", destination_configuration)
        if hybrid_deployment_agent_id is not None:
            pulumi.set(__self__, "hybrid_deployment_agent_id", hybrid_deployment_agent_id)
        if networking_method is not None:
            pulumi.set(__self__, "networking_method", networking_method)
        if pause_after_trial is not None:
            pulumi.set(__self__, "pause_after_trial", pause_after_trial)
        if private_link_id is not None:
            pulumi.set(__self__, "private_link_id", private_link_id)
        if proxy_agent_id is not None:
            pulumi.set(__self__, "proxy_agent_id", proxy_agent_id)
        if run_setup_tests is not None:
            pulumi.set(__self__, "run_setup_tests", run_setup_tests)
        if schedule_type is not None:
            pulumi.set(__self__, "schedule_type", schedule_type)
        if sync_frequency is not None:
            pulumi.set(__self__, "sync_frequency", sync_frequency)
        if trust_certificates is not None:
            pulumi.set(__self__, "trust_certificates", trust_certificates)
        if trust_fingerprints is not None:
            pulumi.set(__self__, "trust_fingerprints", trust_fingerprints)

    @_builtins.property
    @pulumi.getter(name="destinationSchemaNames")
    def destination_schema_names(self) -> pulumi.Input[_builtins.str]:
        """
        Defines how schema names appear in the destination. Supported values: `FIVETRAN_NAMING`, `SOURCE_NAMING`. Changing this forces the connection to be replaced.
        """
        return pulumi.get(self, "destination_schema_names")

    @destination_schema_names.setter
    def destination_schema_names(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "destination_schema_names", value)

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> pulumi.Input[_builtins.str]:
        """
        The unique identifier for the Group (Destination) within the Fivetran system. Changing this forces the connection to be replaced.
        """
        return pulumi.get(self, "group_id")

    @group_id.setter
    def group_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "group_id", value)

    @_builtins.property
    @pulumi.getter
    def service(self) -> pulumi.Input[_builtins.str]:
        """
        The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). Changing this forces the connection to be replaced.
        """
        return pulumi.get(self, "service")

    @service.setter
    def service(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "service", value)

    @_builtins.property
    @pulumi.getter
    def auth(self) -> Optional[Any]:
        """
        Service-specific authorization configuration. The accepted fields are defined by connector metadata at runtime.
        """
        return pulumi.get(self, "auth")

    @auth.setter
    def auth(self, value: Optional[Any]):
        pulumi.set(self, "auth", value)

    @_builtins.property
    @pulumi.getter
    def config(self) -> Optional[Any]:
        """
        Service-specific connection configuration. The accepted fields are defined by connector metadata at runtime.
        """
        return pulumi.get(self, "config")

    @config.setter
    def config(self, value: Optional[Any]):
        pulumi.set(self, "config", value)

    @_builtins.property
    @pulumi.getter(name="connectCardConfig")
    def connect_card_config(self) -> pulumi.Input[Optional['ConnectionV2ConnectCardConfigArgs']]:
        """
        Configuration for the interactive Connect Card setup flow.
        """
        return pulumi.get(self, "connect_card_config")

    @connect_card_config.setter
    def connect_card_config(self, value: pulumi.Input[Optional['ConnectionV2ConnectCardConfigArgs']]):
        pulumi.set(self, "connect_card_config", value)

    @_builtins.property
    @pulumi.getter(name="dailySyncTime")
    def daily_sync_time(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Sync start time. Only used when `sync_frequency` is `1440`.
        """
        return pulumi.get(self, "daily_sync_time")

    @daily_sync_time.setter
    def daily_sync_time(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "daily_sync_time", value)

    @_builtins.property
    @pulumi.getter(name="dataDelaySensitivity")
    def data_delay_sensitivity(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The level of data delay notification threshold. Possible values: `LOW`, `NORMAL`, `HIGH`, `CUSTOM`, `SYNC_FREQUENCY`.
        """
        return pulumi.get(self, "data_delay_sensitivity")

    @data_delay_sensitivity.setter
    def data_delay_sensitivity(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "data_delay_sensitivity", value)

    @_builtins.property
    @pulumi.getter(name="dataDelayThreshold")
    def data_delay_threshold(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Custom sync delay notification threshold in minutes. Only used when `data_delay_sensitivity` is `CUSTOM`.
        """
        return pulumi.get(self, "data_delay_threshold")

    @data_delay_threshold.setter
    def data_delay_threshold(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "data_delay_threshold", value)

    @_builtins.property
    @pulumi.getter(name="destinationConfiguration")
    def destination_configuration(self) -> pulumi.Input[Optional['ConnectionV2DestinationConfigurationArgs']]:
        """
        Destination-specific configuration for the connection.
        """
        return pulumi.get(self, "destination_configuration")

    @destination_configuration.setter
    def destination_configuration(self, value: pulumi.Input[Optional['ConnectionV2DestinationConfigurationArgs']]):
        pulumi.set(self, "destination_configuration", value)

    @_builtins.property
    @pulumi.getter(name="hybridDeploymentAgentId")
    def hybrid_deployment_agent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The hybrid deployment agent ID for the group the connection belongs to.
        """
        return pulumi.get(self, "hybrid_deployment_agent_id")

    @hybrid_deployment_agent_id.setter
    def hybrid_deployment_agent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "hybrid_deployment_agent_id", value)

    @_builtins.property
    @pulumi.getter(name="networkingMethod")
    def networking_method(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        """
        return pulumi.get(self, "networking_method")

    @networking_method.setter
    def networking_method(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "networking_method", value)

    @_builtins.property
    @pulumi.getter(name="pauseAfterTrial")
    def pause_after_trial(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the connection should be paused after the free trial period has ended.
        """
        return pulumi.get(self, "pause_after_trial")

    @pause_after_trial.setter
    def pause_after_trial(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "pause_after_trial", value)

    @_builtins.property
    @pulumi.getter(name="privateLinkId")
    def private_link_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The private link ID. Required when `networking_method` is `PrivateLink`.
        """
        return pulumi.get(self, "private_link_id")

    @private_link_id.setter
    def private_link_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "private_link_id", value)

    @_builtins.property
    @pulumi.getter(name="proxyAgentId")
    def proxy_agent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        """
        return pulumi.get(self, "proxy_agent_id")

    @proxy_agent_id.setter
    def proxy_agent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "proxy_agent_id", value)

    @_builtins.property
    @pulumi.getter(name="runSetupTests")
    def run_setup_tests(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to run setup tests when creating or updating the connection.
        """
        return pulumi.get(self, "run_setup_tests")

    @run_setup_tests.setter
    def run_setup_tests(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "run_setup_tests", value)

    @_builtins.property
    @pulumi.getter(name="scheduleType")
    def schedule_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The connection schedule configuration type. Supported values: `auto`, `manual`.
        """
        return pulumi.get(self, "schedule_type")

    @schedule_type.setter
    def schedule_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "schedule_type", value)

    @_builtins.property
    @pulumi.getter(name="syncFrequency")
    def sync_frequency(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The connection sync frequency in minutes.
        """
        return pulumi.get(self, "sync_frequency")

    @sync_frequency.setter
    def sync_frequency(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "sync_frequency", value)

    @_builtins.property
    @pulumi.getter(name="trustCertificates")
    def trust_certificates(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether Fivetran should trust certificates automatically.
        """
        return pulumi.get(self, "trust_certificates")

    @trust_certificates.setter
    def trust_certificates(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "trust_certificates", value)

    @_builtins.property
    @pulumi.getter(name="trustFingerprints")
    def trust_fingerprints(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether Fivetran should trust SSH fingerprints automatically.
        """
        return pulumi.get(self, "trust_fingerprints")

    @trust_fingerprints.setter
    def trust_fingerprints(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "trust_fingerprints", value)


@pulumi.input_type
class _ConnectionV2State:
    def __init__(__self__, *,
                 auth: Optional[Any] = None,
                 config: Optional[Any] = None,
                 connect_card_config: pulumi.Input[Optional['ConnectionV2ConnectCardConfigArgs']] = None,
                 connected_by: pulumi.Input[Optional[_builtins.str]] = None,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 daily_sync_time: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_sensitivity: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_threshold: pulumi.Input[Optional[_builtins.int]] = None,
                 destination_configuration: pulumi.Input[Optional['ConnectionV2DestinationConfigurationArgs']] = None,
                 destination_schema_names: pulumi.Input[Optional[_builtins.str]] = None,
                 failed_at: pulumi.Input[Optional[_builtins.str]] = None,
                 group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 hybrid_deployment_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 networking_method: pulumi.Input[Optional[_builtins.str]] = None,
                 pause_after_trial: pulumi.Input[Optional[_builtins.bool]] = None,
                 private_link_id: pulumi.Input[Optional[_builtins.str]] = None,
                 proxy_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 run_setup_tests: pulumi.Input[Optional[_builtins.bool]] = None,
                 schedule_type: pulumi.Input[Optional[_builtins.str]] = None,
                 service: pulumi.Input[Optional[_builtins.str]] = None,
                 service_version: pulumi.Input[Optional[_builtins.str]] = None,
                 status: pulumi.Input[Optional['ConnectionV2StatusArgs']] = None,
                 succeeded_at: pulumi.Input[Optional[_builtins.str]] = None,
                 sync_frequency: pulumi.Input[Optional[_builtins.int]] = None,
                 trust_certificates: pulumi.Input[Optional[_builtins.bool]] = None,
                 trust_fingerprints: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering ConnectionV2 resources.

        :param Any auth: Service-specific authorization configuration. The accepted fields are defined by connector metadata at runtime.
        :param Any config: Service-specific connection configuration. The accepted fields are defined by connector metadata at runtime.
        :param pulumi.Input['ConnectionV2ConnectCardConfigArgs'] connect_card_config: Configuration for the interactive Connect Card setup flow.
        :param pulumi.Input[_builtins.str] connected_by: The unique identifier of the user who created the connection in your account.
        :param pulumi.Input[_builtins.str] created_at: The timestamp of the time the connection was created in your account.
        :param pulumi.Input[_builtins.str] daily_sync_time: Sync start time. Only used when `sync_frequency` is `1440`.
        :param pulumi.Input[_builtins.str] data_delay_sensitivity: The level of data delay notification threshold. Possible values: `LOW`, `NORMAL`, `HIGH`, `CUSTOM`, `SYNC_FREQUENCY`.
        :param pulumi.Input[_builtins.int] data_delay_threshold: Custom sync delay notification threshold in minutes. Only used when `data_delay_sensitivity` is `CUSTOM`.
        :param pulumi.Input['ConnectionV2DestinationConfigurationArgs'] destination_configuration: Destination-specific configuration for the connection.
        :param pulumi.Input[_builtins.str] destination_schema_names: Defines how schema names appear in the destination. Supported values: `FIVETRAN_NAMING`, `SOURCE_NAMING`. Changing this forces the connection to be replaced.
        :param pulumi.Input[_builtins.str] failed_at: The timestamp of the time the connection sync failed last time.
        :param pulumi.Input[_builtins.str] group_id: The unique identifier for the Group (Destination) within the Fivetran system. Changing this forces the connection to be replaced.
        :param pulumi.Input[_builtins.str] hybrid_deployment_agent_id: The hybrid deployment agent ID for the group the connection belongs to.
        :param pulumi.Input[_builtins.str] name: The name used both as the connection's name within the Fivetran system and as the source schema's name within your destination.
        :param pulumi.Input[_builtins.str] networking_method: The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        :param pulumi.Input[_builtins.bool] pause_after_trial: Whether the connection should be paused after the free trial period has ended.
        :param pulumi.Input[_builtins.str] private_link_id: The private link ID. Required when `networking_method` is `PrivateLink`.
        :param pulumi.Input[_builtins.str] proxy_agent_id: The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        :param pulumi.Input[_builtins.bool] run_setup_tests: Whether to run setup tests when creating or updating the connection.
        :param pulumi.Input[_builtins.str] schedule_type: The connection schedule configuration type. Supported values: `auto`, `manual`.
        :param pulumi.Input[_builtins.str] service: The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). Changing this forces the connection to be replaced.
        :param pulumi.Input[_builtins.str] service_version: The connection type version within the Fivetran system.
        :param pulumi.Input['ConnectionV2StatusArgs'] status: The current connection status.
        :param pulumi.Input[_builtins.str] succeeded_at: The timestamp of the time the connection sync succeeded last time.
        :param pulumi.Input[_builtins.int] sync_frequency: The connection sync frequency in minutes.
        :param pulumi.Input[_builtins.bool] trust_certificates: Whether Fivetran should trust certificates automatically.
        :param pulumi.Input[_builtins.bool] trust_fingerprints: Whether Fivetran should trust SSH fingerprints automatically.
        """
        if auth is not None:
            pulumi.set(__self__, "auth", auth)
        if config is not None:
            pulumi.set(__self__, "config", config)
        if connect_card_config is not None:
            pulumi.set(__self__, "connect_card_config", connect_card_config)
        if connected_by is not None:
            pulumi.set(__self__, "connected_by", connected_by)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if daily_sync_time is not None:
            pulumi.set(__self__, "daily_sync_time", daily_sync_time)
        if data_delay_sensitivity is not None:
            pulumi.set(__self__, "data_delay_sensitivity", data_delay_sensitivity)
        if data_delay_threshold is not None:
            pulumi.set(__self__, "data_delay_threshold", data_delay_threshold)
        if destination_configuration is not None:
            pulumi.set(__self__, "destination_configuration", destination_configuration)
        if destination_schema_names is not None:
            pulumi.set(__self__, "destination_schema_names", destination_schema_names)
        if failed_at is not None:
            pulumi.set(__self__, "failed_at", failed_at)
        if group_id is not None:
            pulumi.set(__self__, "group_id", group_id)
        if hybrid_deployment_agent_id is not None:
            pulumi.set(__self__, "hybrid_deployment_agent_id", hybrid_deployment_agent_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if networking_method is not None:
            pulumi.set(__self__, "networking_method", networking_method)
        if pause_after_trial is not None:
            pulumi.set(__self__, "pause_after_trial", pause_after_trial)
        if private_link_id is not None:
            pulumi.set(__self__, "private_link_id", private_link_id)
        if proxy_agent_id is not None:
            pulumi.set(__self__, "proxy_agent_id", proxy_agent_id)
        if run_setup_tests is not None:
            pulumi.set(__self__, "run_setup_tests", run_setup_tests)
        if schedule_type is not None:
            pulumi.set(__self__, "schedule_type", schedule_type)
        if service is not None:
            pulumi.set(__self__, "service", service)
        if service_version is not None:
            pulumi.set(__self__, "service_version", service_version)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if succeeded_at is not None:
            pulumi.set(__self__, "succeeded_at", succeeded_at)
        if sync_frequency is not None:
            pulumi.set(__self__, "sync_frequency", sync_frequency)
        if trust_certificates is not None:
            pulumi.set(__self__, "trust_certificates", trust_certificates)
        if trust_fingerprints is not None:
            pulumi.set(__self__, "trust_fingerprints", trust_fingerprints)

    @_builtins.property
    @pulumi.getter
    def auth(self) -> Optional[Any]:
        """
        Service-specific authorization configuration. The accepted fields are defined by connector metadata at runtime.
        """
        return pulumi.get(self, "auth")

    @auth.setter
    def auth(self, value: Optional[Any]):
        pulumi.set(self, "auth", value)

    @_builtins.property
    @pulumi.getter
    def config(self) -> Optional[Any]:
        """
        Service-specific connection configuration. The accepted fields are defined by connector metadata at runtime.
        """
        return pulumi.get(self, "config")

    @config.setter
    def config(self, value: Optional[Any]):
        pulumi.set(self, "config", value)

    @_builtins.property
    @pulumi.getter(name="connectCardConfig")
    def connect_card_config(self) -> pulumi.Input[Optional['ConnectionV2ConnectCardConfigArgs']]:
        """
        Configuration for the interactive Connect Card setup flow.
        """
        return pulumi.get(self, "connect_card_config")

    @connect_card_config.setter
    def connect_card_config(self, value: pulumi.Input[Optional['ConnectionV2ConnectCardConfigArgs']]):
        pulumi.set(self, "connect_card_config", value)

    @_builtins.property
    @pulumi.getter(name="connectedBy")
    def connected_by(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The unique identifier of the user who created the connection in your account.
        """
        return pulumi.get(self, "connected_by")

    @connected_by.setter
    def connected_by(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "connected_by", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The timestamp of the time the connection was created in your account.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="dailySyncTime")
    def daily_sync_time(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Sync start time. Only used when `sync_frequency` is `1440`.
        """
        return pulumi.get(self, "daily_sync_time")

    @daily_sync_time.setter
    def daily_sync_time(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "daily_sync_time", value)

    @_builtins.property
    @pulumi.getter(name="dataDelaySensitivity")
    def data_delay_sensitivity(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The level of data delay notification threshold. Possible values: `LOW`, `NORMAL`, `HIGH`, `CUSTOM`, `SYNC_FREQUENCY`.
        """
        return pulumi.get(self, "data_delay_sensitivity")

    @data_delay_sensitivity.setter
    def data_delay_sensitivity(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "data_delay_sensitivity", value)

    @_builtins.property
    @pulumi.getter(name="dataDelayThreshold")
    def data_delay_threshold(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Custom sync delay notification threshold in minutes. Only used when `data_delay_sensitivity` is `CUSTOM`.
        """
        return pulumi.get(self, "data_delay_threshold")

    @data_delay_threshold.setter
    def data_delay_threshold(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "data_delay_threshold", value)

    @_builtins.property
    @pulumi.getter(name="destinationConfiguration")
    def destination_configuration(self) -> pulumi.Input[Optional['ConnectionV2DestinationConfigurationArgs']]:
        """
        Destination-specific configuration for the connection.
        """
        return pulumi.get(self, "destination_configuration")

    @destination_configuration.setter
    def destination_configuration(self, value: pulumi.Input[Optional['ConnectionV2DestinationConfigurationArgs']]):
        pulumi.set(self, "destination_configuration", value)

    @_builtins.property
    @pulumi.getter(name="destinationSchemaNames")
    def destination_schema_names(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Defines how schema names appear in the destination. Supported values: `FIVETRAN_NAMING`, `SOURCE_NAMING`. Changing this forces the connection to be replaced.
        """
        return pulumi.get(self, "destination_schema_names")

    @destination_schema_names.setter
    def destination_schema_names(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "destination_schema_names", value)

    @_builtins.property
    @pulumi.getter(name="failedAt")
    def failed_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The timestamp of the time the connection sync failed last time.
        """
        return pulumi.get(self, "failed_at")

    @failed_at.setter
    def failed_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "failed_at", value)

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The unique identifier for the Group (Destination) within the Fivetran system. Changing this forces the connection to be replaced.
        """
        return pulumi.get(self, "group_id")

    @group_id.setter
    def group_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "group_id", value)

    @_builtins.property
    @pulumi.getter(name="hybridDeploymentAgentId")
    def hybrid_deployment_agent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The hybrid deployment agent ID for the group the connection belongs to.
        """
        return pulumi.get(self, "hybrid_deployment_agent_id")

    @hybrid_deployment_agent_id.setter
    def hybrid_deployment_agent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "hybrid_deployment_agent_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name used both as the connection's name within the Fivetran system and as the source schema's name within your destination.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="networkingMethod")
    def networking_method(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        """
        return pulumi.get(self, "networking_method")

    @networking_method.setter
    def networking_method(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "networking_method", value)

    @_builtins.property
    @pulumi.getter(name="pauseAfterTrial")
    def pause_after_trial(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the connection should be paused after the free trial period has ended.
        """
        return pulumi.get(self, "pause_after_trial")

    @pause_after_trial.setter
    def pause_after_trial(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "pause_after_trial", value)

    @_builtins.property
    @pulumi.getter(name="privateLinkId")
    def private_link_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The private link ID. Required when `networking_method` is `PrivateLink`.
        """
        return pulumi.get(self, "private_link_id")

    @private_link_id.setter
    def private_link_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "private_link_id", value)

    @_builtins.property
    @pulumi.getter(name="proxyAgentId")
    def proxy_agent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        """
        return pulumi.get(self, "proxy_agent_id")

    @proxy_agent_id.setter
    def proxy_agent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "proxy_agent_id", value)

    @_builtins.property
    @pulumi.getter(name="runSetupTests")
    def run_setup_tests(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to run setup tests when creating or updating the connection.
        """
        return pulumi.get(self, "run_setup_tests")

    @run_setup_tests.setter
    def run_setup_tests(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "run_setup_tests", value)

    @_builtins.property
    @pulumi.getter(name="scheduleType")
    def schedule_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The connection schedule configuration type. Supported values: `auto`, `manual`.
        """
        return pulumi.get(self, "schedule_type")

    @schedule_type.setter
    def schedule_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "schedule_type", value)

    @_builtins.property
    @pulumi.getter
    def service(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). Changing this forces the connection to be replaced.
        """
        return pulumi.get(self, "service")

    @service.setter
    def service(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "service", value)

    @_builtins.property
    @pulumi.getter(name="serviceVersion")
    def service_version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The connection type version within the Fivetran system.
        """
        return pulumi.get(self, "service_version")

    @service_version.setter
    def service_version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "service_version", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional['ConnectionV2StatusArgs']]:
        """
        The current connection status.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional['ConnectionV2StatusArgs']]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="succeededAt")
    def succeeded_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The timestamp of the time the connection sync succeeded last time.
        """
        return pulumi.get(self, "succeeded_at")

    @succeeded_at.setter
    def succeeded_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "succeeded_at", value)

    @_builtins.property
    @pulumi.getter(name="syncFrequency")
    def sync_frequency(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The connection sync frequency in minutes.
        """
        return pulumi.get(self, "sync_frequency")

    @sync_frequency.setter
    def sync_frequency(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "sync_frequency", value)

    @_builtins.property
    @pulumi.getter(name="trustCertificates")
    def trust_certificates(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether Fivetran should trust certificates automatically.
        """
        return pulumi.get(self, "trust_certificates")

    @trust_certificates.setter
    def trust_certificates(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "trust_certificates", value)

    @_builtins.property
    @pulumi.getter(name="trustFingerprints")
    def trust_fingerprints(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether Fivetran should trust SSH fingerprints automatically.
        """
        return pulumi.get(self, "trust_fingerprints")

    @trust_fingerprints.setter
    def trust_fingerprints(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "trust_fingerprints", value)


@pulumi.type_token("fivetran:index/connectionV2:ConnectionV2")
class ConnectionV2(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auth: Optional[Any] = None,
                 config: Optional[Any] = None,
                 connect_card_config: pulumi.Input[Optional[Union['ConnectionV2ConnectCardConfigArgs', 'ConnectionV2ConnectCardConfigArgsDict']]] = None,
                 daily_sync_time: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_sensitivity: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_threshold: pulumi.Input[Optional[_builtins.int]] = None,
                 destination_configuration: pulumi.Input[Optional[Union['ConnectionV2DestinationConfigurationArgs', 'ConnectionV2DestinationConfigurationArgsDict']]] = None,
                 destination_schema_names: pulumi.Input[Optional[_builtins.str]] = None,
                 group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 hybrid_deployment_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 networking_method: pulumi.Input[Optional[_builtins.str]] = None,
                 pause_after_trial: pulumi.Input[Optional[_builtins.bool]] = None,
                 private_link_id: pulumi.Input[Optional[_builtins.str]] = None,
                 proxy_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 run_setup_tests: pulumi.Input[Optional[_builtins.bool]] = None,
                 schedule_type: pulumi.Input[Optional[_builtins.str]] = None,
                 service: pulumi.Input[Optional[_builtins.str]] = None,
                 sync_frequency: pulumi.Input[Optional[_builtins.int]] = None,
                 trust_certificates: pulumi.Input[Optional[_builtins.bool]] = None,
                 trust_fingerprints: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        > **Alpha:** This resource is in alpha and its schema and behavior may change without notice. Not recommended for production use.

        Manages a Fivetran connection. Unlike `Connector`/`Connection`, `config` and `auth` are provided as dynamic, service-specific objects: their accepted fields, types, and required/readonly/immutable rules are resolved from connector metadata at plan time rather than from a fixed schema. This means the same resource works across services (e.g. `s3`, `postgres`, `fivetran_log`) without a per-service Terraform schema.

        Pause state is managed separately via `ConnectionV2PauseState`; this resource does not expose a `paused` attribute. **New connections are always created paused.** To start syncing, add a linked `ConnectionV2PauseState` resource with `paused = false`.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_provider_fivetran as fivetran

        connection = fivetran.ConnectionV2("connection",
            service="fivetran_log",
            group_id="group_id",
            config={
                "schema": "my_schema",
            })
        # The connection above is created paused. Unpause it to start syncing:
        pause_state = fivetran.ConnectionV2PauseState("pause_state",
            connection_id=connection.id,
            paused=False)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param Any auth: Service-specific authorization configuration. The accepted fields are defined by connector metadata at runtime.
        :param Any config: Service-specific connection configuration. The accepted fields are defined by connector metadata at runtime.
        :param pulumi.Input[Union['ConnectionV2ConnectCardConfigArgs', 'ConnectionV2ConnectCardConfigArgsDict']] connect_card_config: Configuration for the interactive Connect Card setup flow.
        :param pulumi.Input[_builtins.str] daily_sync_time: Sync start time. Only used when `sync_frequency` is `1440`.
        :param pulumi.Input[_builtins.str] data_delay_sensitivity: The level of data delay notification threshold. Possible values: `LOW`, `NORMAL`, `HIGH`, `CUSTOM`, `SYNC_FREQUENCY`.
        :param pulumi.Input[_builtins.int] data_delay_threshold: Custom sync delay notification threshold in minutes. Only used when `data_delay_sensitivity` is `CUSTOM`.
        :param pulumi.Input[Union['ConnectionV2DestinationConfigurationArgs', 'ConnectionV2DestinationConfigurationArgsDict']] destination_configuration: Destination-specific configuration for the connection.
        :param pulumi.Input[_builtins.str] destination_schema_names: Defines how schema names appear in the destination. Supported values: `FIVETRAN_NAMING`, `SOURCE_NAMING`. Changing this forces the connection to be replaced.
        :param pulumi.Input[_builtins.str] group_id: The unique identifier for the Group (Destination) within the Fivetran system. Changing this forces the connection to be replaced.
        :param pulumi.Input[_builtins.str] hybrid_deployment_agent_id: The hybrid deployment agent ID for the group the connection belongs to.
        :param pulumi.Input[_builtins.str] networking_method: The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        :param pulumi.Input[_builtins.bool] pause_after_trial: Whether the connection should be paused after the free trial period has ended.
        :param pulumi.Input[_builtins.str] private_link_id: The private link ID. Required when `networking_method` is `PrivateLink`.
        :param pulumi.Input[_builtins.str] proxy_agent_id: The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        :param pulumi.Input[_builtins.bool] run_setup_tests: Whether to run setup tests when creating or updating the connection.
        :param pulumi.Input[_builtins.str] schedule_type: The connection schedule configuration type. Supported values: `auto`, `manual`.
        :param pulumi.Input[_builtins.str] service: The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). Changing this forces the connection to be replaced.
        :param pulumi.Input[_builtins.int] sync_frequency: The connection sync frequency in minutes.
        :param pulumi.Input[_builtins.bool] trust_certificates: Whether Fivetran should trust certificates automatically.
        :param pulumi.Input[_builtins.bool] trust_fingerprints: Whether Fivetran should trust SSH fingerprints automatically.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ConnectionV2Args,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        > **Alpha:** This resource is in alpha and its schema and behavior may change without notice. Not recommended for production use.

        Manages a Fivetran connection. Unlike `Connector`/`Connection`, `config` and `auth` are provided as dynamic, service-specific objects: their accepted fields, types, and required/readonly/immutable rules are resolved from connector metadata at plan time rather than from a fixed schema. This means the same resource works across services (e.g. `s3`, `postgres`, `fivetran_log`) without a per-service Terraform schema.

        Pause state is managed separately via `ConnectionV2PauseState`; this resource does not expose a `paused` attribute. **New connections are always created paused.** To start syncing, add a linked `ConnectionV2PauseState` resource with `paused = false`.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_provider_fivetran as fivetran

        connection = fivetran.ConnectionV2("connection",
            service="fivetran_log",
            group_id="group_id",
            config={
                "schema": "my_schema",
            })
        # The connection above is created paused. Unpause it to start syncing:
        pause_state = fivetran.ConnectionV2PauseState("pause_state",
            connection_id=connection.id,
            paused=False)
        ```


        :param str resource_name: The name of the resource.
        :param ConnectionV2Args args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ConnectionV2Args, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auth: Optional[Any] = None,
                 config: Optional[Any] = None,
                 connect_card_config: pulumi.Input[Optional[Union['ConnectionV2ConnectCardConfigArgs', 'ConnectionV2ConnectCardConfigArgsDict']]] = None,
                 daily_sync_time: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_sensitivity: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_threshold: pulumi.Input[Optional[_builtins.int]] = None,
                 destination_configuration: pulumi.Input[Optional[Union['ConnectionV2DestinationConfigurationArgs', 'ConnectionV2DestinationConfigurationArgsDict']]] = None,
                 destination_schema_names: pulumi.Input[Optional[_builtins.str]] = None,
                 group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 hybrid_deployment_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 networking_method: pulumi.Input[Optional[_builtins.str]] = None,
                 pause_after_trial: pulumi.Input[Optional[_builtins.bool]] = None,
                 private_link_id: pulumi.Input[Optional[_builtins.str]] = None,
                 proxy_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 run_setup_tests: pulumi.Input[Optional[_builtins.bool]] = None,
                 schedule_type: pulumi.Input[Optional[_builtins.str]] = None,
                 service: pulumi.Input[Optional[_builtins.str]] = None,
                 sync_frequency: pulumi.Input[Optional[_builtins.int]] = None,
                 trust_certificates: pulumi.Input[Optional[_builtins.bool]] = None,
                 trust_fingerprints: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ConnectionV2Args.__new__(ConnectionV2Args)

            __props__.__dict__["auth"] = None if auth is None else pulumi.Output.secret(auth)
            __props__.__dict__["config"] = config
            __props__.__dict__["connect_card_config"] = connect_card_config
            __props__.__dict__["daily_sync_time"] = daily_sync_time
            __props__.__dict__["data_delay_sensitivity"] = data_delay_sensitivity
            __props__.__dict__["data_delay_threshold"] = data_delay_threshold
            __props__.__dict__["destination_configuration"] = destination_configuration
            if destination_schema_names is None and not opts.urn:
                raise TypeError("Missing required property 'destination_schema_names'")
            __props__.__dict__["destination_schema_names"] = destination_schema_names
            if group_id is None and not opts.urn:
                raise TypeError("Missing required property 'group_id'")
            __props__.__dict__["group_id"] = group_id
            __props__.__dict__["hybrid_deployment_agent_id"] = hybrid_deployment_agent_id
            __props__.__dict__["networking_method"] = networking_method
            __props__.__dict__["pause_after_trial"] = pause_after_trial
            __props__.__dict__["private_link_id"] = private_link_id
            __props__.__dict__["proxy_agent_id"] = proxy_agent_id
            __props__.__dict__["run_setup_tests"] = run_setup_tests
            __props__.__dict__["schedule_type"] = schedule_type
            if service is None and not opts.urn:
                raise TypeError("Missing required property 'service'")
            __props__.__dict__["service"] = service
            __props__.__dict__["sync_frequency"] = sync_frequency
            __props__.__dict__["trust_certificates"] = trust_certificates
            __props__.__dict__["trust_fingerprints"] = trust_fingerprints
            __props__.__dict__["connected_by"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["failed_at"] = None
            __props__.__dict__["name"] = None
            __props__.__dict__["service_version"] = None
            __props__.__dict__["status"] = None
            __props__.__dict__["succeeded_at"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["auth"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ConnectionV2, __self__).__init__(
            'fivetran:index/connectionV2:ConnectionV2',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            auth: Optional[Any] = None,
            config: Optional[Any] = None,
            connect_card_config: pulumi.Input[Optional[Union['ConnectionV2ConnectCardConfigArgs', 'ConnectionV2ConnectCardConfigArgsDict']]] = None,
            connected_by: pulumi.Input[Optional[_builtins.str]] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            daily_sync_time: pulumi.Input[Optional[_builtins.str]] = None,
            data_delay_sensitivity: pulumi.Input[Optional[_builtins.str]] = None,
            data_delay_threshold: pulumi.Input[Optional[_builtins.int]] = None,
            destination_configuration: pulumi.Input[Optional[Union['ConnectionV2DestinationConfigurationArgs', 'ConnectionV2DestinationConfigurationArgsDict']]] = None,
            destination_schema_names: pulumi.Input[Optional[_builtins.str]] = None,
            failed_at: pulumi.Input[Optional[_builtins.str]] = None,
            group_id: pulumi.Input[Optional[_builtins.str]] = None,
            hybrid_deployment_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            networking_method: pulumi.Input[Optional[_builtins.str]] = None,
            pause_after_trial: pulumi.Input[Optional[_builtins.bool]] = None,
            private_link_id: pulumi.Input[Optional[_builtins.str]] = None,
            proxy_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
            run_setup_tests: pulumi.Input[Optional[_builtins.bool]] = None,
            schedule_type: pulumi.Input[Optional[_builtins.str]] = None,
            service: pulumi.Input[Optional[_builtins.str]] = None,
            service_version: pulumi.Input[Optional[_builtins.str]] = None,
            status: pulumi.Input[Optional[Union['ConnectionV2StatusArgs', 'ConnectionV2StatusArgsDict']]] = None,
            succeeded_at: pulumi.Input[Optional[_builtins.str]] = None,
            sync_frequency: pulumi.Input[Optional[_builtins.int]] = None,
            trust_certificates: pulumi.Input[Optional[_builtins.bool]] = None,
            trust_fingerprints: pulumi.Input[Optional[_builtins.bool]] = None) -> 'ConnectionV2':
        """
        Get an existing ConnectionV2 resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param Any auth: Service-specific authorization configuration. The accepted fields are defined by connector metadata at runtime.
        :param Any config: Service-specific connection configuration. The accepted fields are defined by connector metadata at runtime.
        :param pulumi.Input[Union['ConnectionV2ConnectCardConfigArgs', 'ConnectionV2ConnectCardConfigArgsDict']] connect_card_config: Configuration for the interactive Connect Card setup flow.
        :param pulumi.Input[_builtins.str] connected_by: The unique identifier of the user who created the connection in your account.
        :param pulumi.Input[_builtins.str] created_at: The timestamp of the time the connection was created in your account.
        :param pulumi.Input[_builtins.str] daily_sync_time: Sync start time. Only used when `sync_frequency` is `1440`.
        :param pulumi.Input[_builtins.str] data_delay_sensitivity: The level of data delay notification threshold. Possible values: `LOW`, `NORMAL`, `HIGH`, `CUSTOM`, `SYNC_FREQUENCY`.
        :param pulumi.Input[_builtins.int] data_delay_threshold: Custom sync delay notification threshold in minutes. Only used when `data_delay_sensitivity` is `CUSTOM`.
        :param pulumi.Input[Union['ConnectionV2DestinationConfigurationArgs', 'ConnectionV2DestinationConfigurationArgsDict']] destination_configuration: Destination-specific configuration for the connection.
        :param pulumi.Input[_builtins.str] destination_schema_names: Defines how schema names appear in the destination. Supported values: `FIVETRAN_NAMING`, `SOURCE_NAMING`. Changing this forces the connection to be replaced.
        :param pulumi.Input[_builtins.str] failed_at: The timestamp of the time the connection sync failed last time.
        :param pulumi.Input[_builtins.str] group_id: The unique identifier for the Group (Destination) within the Fivetran system. Changing this forces the connection to be replaced.
        :param pulumi.Input[_builtins.str] hybrid_deployment_agent_id: The hybrid deployment agent ID for the group the connection belongs to.
        :param pulumi.Input[_builtins.str] name: The name used both as the connection's name within the Fivetran system and as the source schema's name within your destination.
        :param pulumi.Input[_builtins.str] networking_method: The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        :param pulumi.Input[_builtins.bool] pause_after_trial: Whether the connection should be paused after the free trial period has ended.
        :param pulumi.Input[_builtins.str] private_link_id: The private link ID. Required when `networking_method` is `PrivateLink`.
        :param pulumi.Input[_builtins.str] proxy_agent_id: The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        :param pulumi.Input[_builtins.bool] run_setup_tests: Whether to run setup tests when creating or updating the connection.
        :param pulumi.Input[_builtins.str] schedule_type: The connection schedule configuration type. Supported values: `auto`, `manual`.
        :param pulumi.Input[_builtins.str] service: The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). Changing this forces the connection to be replaced.
        :param pulumi.Input[_builtins.str] service_version: The connection type version within the Fivetran system.
        :param pulumi.Input[Union['ConnectionV2StatusArgs', 'ConnectionV2StatusArgsDict']] status: The current connection status.
        :param pulumi.Input[_builtins.str] succeeded_at: The timestamp of the time the connection sync succeeded last time.
        :param pulumi.Input[_builtins.int] sync_frequency: The connection sync frequency in minutes.
        :param pulumi.Input[_builtins.bool] trust_certificates: Whether Fivetran should trust certificates automatically.
        :param pulumi.Input[_builtins.bool] trust_fingerprints: Whether Fivetran should trust SSH fingerprints automatically.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ConnectionV2State.__new__(_ConnectionV2State)

        __props__.__dict__["auth"] = auth
        __props__.__dict__["config"] = config
        __props__.__dict__["connect_card_config"] = connect_card_config
        __props__.__dict__["connected_by"] = connected_by
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["daily_sync_time"] = daily_sync_time
        __props__.__dict__["data_delay_sensitivity"] = data_delay_sensitivity
        __props__.__dict__["data_delay_threshold"] = data_delay_threshold
        __props__.__dict__["destination_configuration"] = destination_configuration
        __props__.__dict__["destination_schema_names"] = destination_schema_names
        __props__.__dict__["failed_at"] = failed_at
        __props__.__dict__["group_id"] = group_id
        __props__.__dict__["hybrid_deployment_agent_id"] = hybrid_deployment_agent_id
        __props__.__dict__["name"] = name
        __props__.__dict__["networking_method"] = networking_method
        __props__.__dict__["pause_after_trial"] = pause_after_trial
        __props__.__dict__["private_link_id"] = private_link_id
        __props__.__dict__["proxy_agent_id"] = proxy_agent_id
        __props__.__dict__["run_setup_tests"] = run_setup_tests
        __props__.__dict__["schedule_type"] = schedule_type
        __props__.__dict__["service"] = service
        __props__.__dict__["service_version"] = service_version
        __props__.__dict__["status"] = status
        __props__.__dict__["succeeded_at"] = succeeded_at
        __props__.__dict__["sync_frequency"] = sync_frequency
        __props__.__dict__["trust_certificates"] = trust_certificates
        __props__.__dict__["trust_fingerprints"] = trust_fingerprints
        return ConnectionV2(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def auth(self) -> pulumi.Output[Optional[Any]]:
        """
        Service-specific authorization configuration. The accepted fields are defined by connector metadata at runtime.
        """
        return pulumi.get(self, "auth")

    @_builtins.property
    @pulumi.getter
    def config(self) -> pulumi.Output[Any]:
        """
        Service-specific connection configuration. The accepted fields are defined by connector metadata at runtime.
        """
        return pulumi.get(self, "config")

    @_builtins.property
    @pulumi.getter(name="connectCardConfig")
    def connect_card_config(self) -> pulumi.Output[Optional['outputs.ConnectionV2ConnectCardConfig']]:
        """
        Configuration for the interactive Connect Card setup flow.
        """
        return pulumi.get(self, "connect_card_config")

    @_builtins.property
    @pulumi.getter(name="connectedBy")
    def connected_by(self) -> pulumi.Output[_builtins.str]:
        """
        The unique identifier of the user who created the connection in your account.
        """
        return pulumi.get(self, "connected_by")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        The timestamp of the time the connection was created in your account.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="dailySyncTime")
    def daily_sync_time(self) -> pulumi.Output[_builtins.str]:
        """
        Sync start time. Only used when `sync_frequency` is `1440`.
        """
        return pulumi.get(self, "daily_sync_time")

    @_builtins.property
    @pulumi.getter(name="dataDelaySensitivity")
    def data_delay_sensitivity(self) -> pulumi.Output[_builtins.str]:
        """
        The level of data delay notification threshold. Possible values: `LOW`, `NORMAL`, `HIGH`, `CUSTOM`, `SYNC_FREQUENCY`.
        """
        return pulumi.get(self, "data_delay_sensitivity")

    @_builtins.property
    @pulumi.getter(name="dataDelayThreshold")
    def data_delay_threshold(self) -> pulumi.Output[_builtins.int]:
        """
        Custom sync delay notification threshold in minutes. Only used when `data_delay_sensitivity` is `CUSTOM`.
        """
        return pulumi.get(self, "data_delay_threshold")

    @_builtins.property
    @pulumi.getter(name="destinationConfiguration")
    def destination_configuration(self) -> pulumi.Output['outputs.ConnectionV2DestinationConfiguration']:
        """
        Destination-specific configuration for the connection.
        """
        return pulumi.get(self, "destination_configuration")

    @_builtins.property
    @pulumi.getter(name="destinationSchemaNames")
    def destination_schema_names(self) -> pulumi.Output[_builtins.str]:
        """
        Defines how schema names appear in the destination. Supported values: `FIVETRAN_NAMING`, `SOURCE_NAMING`. Changing this forces the connection to be replaced.
        """
        return pulumi.get(self, "destination_schema_names")

    @_builtins.property
    @pulumi.getter(name="failedAt")
    def failed_at(self) -> pulumi.Output[_builtins.str]:
        """
        The timestamp of the time the connection sync failed last time.
        """
        return pulumi.get(self, "failed_at")

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> pulumi.Output[_builtins.str]:
        """
        The unique identifier for the Group (Destination) within the Fivetran system. Changing this forces the connection to be replaced.
        """
        return pulumi.get(self, "group_id")

    @_builtins.property
    @pulumi.getter(name="hybridDeploymentAgentId")
    def hybrid_deployment_agent_id(self) -> pulumi.Output[_builtins.str]:
        """
        The hybrid deployment agent ID for the group the connection belongs to.
        """
        return pulumi.get(self, "hybrid_deployment_agent_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name used both as the connection's name within the Fivetran system and as the source schema's name within your destination.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="networkingMethod")
    def networking_method(self) -> pulumi.Output[_builtins.str]:
        """
        The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        """
        return pulumi.get(self, "networking_method")

    @_builtins.property
    @pulumi.getter(name="pauseAfterTrial")
    def pause_after_trial(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the connection should be paused after the free trial period has ended.
        """
        return pulumi.get(self, "pause_after_trial")

    @_builtins.property
    @pulumi.getter(name="privateLinkId")
    def private_link_id(self) -> pulumi.Output[_builtins.str]:
        """
        The private link ID. Required when `networking_method` is `PrivateLink`.
        """
        return pulumi.get(self, "private_link_id")

    @_builtins.property
    @pulumi.getter(name="proxyAgentId")
    def proxy_agent_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        """
        return pulumi.get(self, "proxy_agent_id")

    @_builtins.property
    @pulumi.getter(name="runSetupTests")
    def run_setup_tests(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether to run setup tests when creating or updating the connection.
        """
        return pulumi.get(self, "run_setup_tests")

    @_builtins.property
    @pulumi.getter(name="scheduleType")
    def schedule_type(self) -> pulumi.Output[_builtins.str]:
        """
        The connection schedule configuration type. Supported values: `auto`, `manual`.
        """
        return pulumi.get(self, "schedule_type")

    @_builtins.property
    @pulumi.getter
    def service(self) -> pulumi.Output[_builtins.str]:
        """
        The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). Changing this forces the connection to be replaced.
        """
        return pulumi.get(self, "service")

    @_builtins.property
    @pulumi.getter(name="serviceVersion")
    def service_version(self) -> pulumi.Output[_builtins.str]:
        """
        The connection type version within the Fivetran system.
        """
        return pulumi.get(self, "service_version")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output['outputs.ConnectionV2Status']:
        """
        The current connection status.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="succeededAt")
    def succeeded_at(self) -> pulumi.Output[_builtins.str]:
        """
        The timestamp of the time the connection sync succeeded last time.
        """
        return pulumi.get(self, "succeeded_at")

    @_builtins.property
    @pulumi.getter(name="syncFrequency")
    def sync_frequency(self) -> pulumi.Output[_builtins.int]:
        """
        The connection sync frequency in minutes.
        """
        return pulumi.get(self, "sync_frequency")

    @_builtins.property
    @pulumi.getter(name="trustCertificates")
    def trust_certificates(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether Fivetran should trust certificates automatically.
        """
        return pulumi.get(self, "trust_certificates")

    @_builtins.property
    @pulumi.getter(name="trustFingerprints")
    def trust_fingerprints(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether Fivetran should trust SSH fingerprints automatically.
        """
        return pulumi.get(self, "trust_fingerprints")

