# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ConnectorSdkPackageArgs', 'ConnectorSdkPackage']

@pulumi.input_type
class ConnectorSdkPackageArgs:
    def __init__(__self__, *,
                 file_path: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a ConnectorSdkPackage resource.

        :param pulumi.Input[_builtins.str] file_path: Path to the .zip file to upload. File is read during plan (for change detection) and during apply (for upload).
        """
        pulumi.set(__self__, "file_path", file_path)

    @_builtins.property
    @pulumi.getter(name="filePath")
    def file_path(self) -> pulumi.Input[_builtins.str]:
        """
        Path to the .zip file to upload. File is read during plan (for change detection) and during apply (for upload).
        """
        return pulumi.get(self, "file_path")

    @file_path.setter
    def file_path(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "file_path", value)


@pulumi.input_type
class _ConnectorSdkPackageState:
    def __init__(__self__, *,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 file_path: pulumi.Input[Optional[_builtins.str]] = None,
                 file_sha256_hash: pulumi.Input[Optional[_builtins.str]] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ConnectorSdkPackage resources.

        :param pulumi.Input[_builtins.str] created_at: Timestamp when the package was created.
        :param pulumi.Input[_builtins.str] file_path: Path to the .zip file to upload. File is read during plan (for change detection) and during apply (for upload).
        :param pulumi.Input[_builtins.str] file_sha256_hash: SHA-256 hash of the uploaded file as computed and stored by the API. Used for upstream drift detection.
        :param pulumi.Input[_builtins.str] updated_at: Timestamp when the package was last updated.
        """
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if file_path is not None:
            pulumi.set(__self__, "file_path", file_path)
        if file_sha256_hash is not None:
            pulumi.set(__self__, "file_sha256_hash", file_sha256_hash)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Timestamp when the package was created.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="filePath")
    def file_path(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Path to the .zip file to upload. File is read during plan (for change detection) and during apply (for upload).
        """
        return pulumi.get(self, "file_path")

    @file_path.setter
    def file_path(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "file_path", value)

    @_builtins.property
    @pulumi.getter(name="fileSha256Hash")
    def file_sha256_hash(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SHA-256 hash of the uploaded file as computed and stored by the API. Used for upstream drift detection.
        """
        return pulumi.get(self, "file_sha256_hash")

    @file_sha256_hash.setter
    def file_sha256_hash(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "file_sha256_hash", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Timestamp when the package was last updated.
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updated_at", value)


@pulumi.type_token("fivetran:index/connectorSdkPackage:ConnectorSdkPackage")
class ConnectorSdkPackage(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 file_path: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        This resource allows you to upload and manage a Connector SDK code package. The `.zip` file referenced by `file_path` is uploaded to Fivetran, and the resulting package ID can be referenced by a `Connector` resource with `service = "connector_sdk"`.

        The provider computes a SHA-256 hash of the file during `pulumi preview`, so changes to the `.zip` contents are detected without relying on metadata such as modification times.

        ## Import

        1. To import an existing `ConnectorSdkPackage` resource into your Terraform state, you need to get the package ID (a two-word identifier, e.g. `distribute_panning`) from the Fivetran UI or API.

        2. Define an empty resource in your `.tf` configuration:

        ```python
        import pulumi
        import pulumi_provider_fivetran as fivetran

        my_imported_sdk_package = fivetran.ConnectorSdkPackage("my_imported_sdk_package")
        ```

        3. Run the `pulumi import` command:

        ```sh
        $ pulumi import fivetran:index/connectorSdkPackage:ConnectorSdkPackage my_imported_sdk_package {package_id}
        ```

        4. Use the `terraform state show` command to get the values from the state:

        ```sh
        terraform state show 'fivetran_connector_sdk_package.my_imported_sdk_package'
        ```

        5. Copy the computed values and paste them into your `.tf` configuration. Then set `file_path` to the local path of the `.zip` file that was originally uploaded. The `file_path` attribute is not returned by the API, so it cannot be populated by import alone — you must supply it manually.

        > NOTE: After import, the first `pulumi preview` may show a non-destructive in-place update for `file_path`. As long as the SHA-256 hash of the local file matches the imported `file_sha256_hash`, the subsequent `apply` will only reconcile state and will not re-upload the file.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] file_path: Path to the .zip file to upload. File is read during plan (for change detection) and during apply (for upload).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ConnectorSdkPackageArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        This resource allows you to upload and manage a Connector SDK code package. The `.zip` file referenced by `file_path` is uploaded to Fivetran, and the resulting package ID can be referenced by a `Connector` resource with `service = "connector_sdk"`.

        The provider computes a SHA-256 hash of the file during `pulumi preview`, so changes to the `.zip` contents are detected without relying on metadata such as modification times.

        ## Import

        1. To import an existing `ConnectorSdkPackage` resource into your Terraform state, you need to get the package ID (a two-word identifier, e.g. `distribute_panning`) from the Fivetran UI or API.

        2. Define an empty resource in your `.tf` configuration:

        ```python
        import pulumi
        import pulumi_provider_fivetran as fivetran

        my_imported_sdk_package = fivetran.ConnectorSdkPackage("my_imported_sdk_package")
        ```

        3. Run the `pulumi import` command:

        ```sh
        $ pulumi import fivetran:index/connectorSdkPackage:ConnectorSdkPackage my_imported_sdk_package {package_id}
        ```

        4. Use the `terraform state show` command to get the values from the state:

        ```sh
        terraform state show 'fivetran_connector_sdk_package.my_imported_sdk_package'
        ```

        5. Copy the computed values and paste them into your `.tf` configuration. Then set `file_path` to the local path of the `.zip` file that was originally uploaded. The `file_path` attribute is not returned by the API, so it cannot be populated by import alone — you must supply it manually.

        > NOTE: After import, the first `pulumi preview` may show a non-destructive in-place update for `file_path`. As long as the SHA-256 hash of the local file matches the imported `file_sha256_hash`, the subsequent `apply` will only reconcile state and will not re-upload the file.


        :param str resource_name: The name of the resource.
        :param ConnectorSdkPackageArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ConnectorSdkPackageArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 file_path: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ConnectorSdkPackageArgs.__new__(ConnectorSdkPackageArgs)

            if file_path is None and not opts.urn:
                raise TypeError("Missing required property 'file_path'")
            __props__.__dict__["file_path"] = file_path
            __props__.__dict__["created_at"] = None
            __props__.__dict__["file_sha256_hash"] = None
            __props__.__dict__["updated_at"] = None
        super(ConnectorSdkPackage, __self__).__init__(
            'fivetran:index/connectorSdkPackage:ConnectorSdkPackage',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            file_path: pulumi.Input[Optional[_builtins.str]] = None,
            file_sha256_hash: pulumi.Input[Optional[_builtins.str]] = None,
            updated_at: pulumi.Input[Optional[_builtins.str]] = None) -> 'ConnectorSdkPackage':
        """
        Get an existing ConnectorSdkPackage resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] created_at: Timestamp when the package was created.
        :param pulumi.Input[_builtins.str] file_path: Path to the .zip file to upload. File is read during plan (for change detection) and during apply (for upload).
        :param pulumi.Input[_builtins.str] file_sha256_hash: SHA-256 hash of the uploaded file as computed and stored by the API. Used for upstream drift detection.
        :param pulumi.Input[_builtins.str] updated_at: Timestamp when the package was last updated.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ConnectorSdkPackageState.__new__(_ConnectorSdkPackageState)

        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["file_path"] = file_path
        __props__.__dict__["file_sha256_hash"] = file_sha256_hash
        __props__.__dict__["updated_at"] = updated_at
        return ConnectorSdkPackage(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp when the package was created.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="filePath")
    def file_path(self) -> pulumi.Output[_builtins.str]:
        """
        Path to the .zip file to upload. File is read during plan (for change detection) and during apply (for upload).
        """
        return pulumi.get(self, "file_path")

    @_builtins.property
    @pulumi.getter(name="fileSha256Hash")
    def file_sha256_hash(self) -> pulumi.Output[_builtins.str]:
        """
        SHA-256 hash of the uploaded file as computed and stored by the API. Used for upstream drift detection.
        """
        return pulumi.get(self, "file_sha256_hash")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp when the package was last updated.
        """
        return pulumi.get(self, "updated_at")

