# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ConnectionArgs', 'Connection']

@pulumi.input_type
class ConnectionArgs:
    def __init__(__self__, *,
                 group_id: pulumi.Input[_builtins.str],
                 service: pulumi.Input[_builtins.str],
                 config: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_sensitivity: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_threshold: pulumi.Input[Optional[_builtins.int]] = None,
                 destination_schema: pulumi.Input[Optional['ConnectionDestinationSchemaArgs']] = None,
                 hybrid_deployment_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 networking_method: pulumi.Input[Optional[_builtins.str]] = None,
                 private_link_id: pulumi.Input[Optional[_builtins.str]] = None,
                 proxy_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 run_setup_tests: pulumi.Input[Optional[_builtins.bool]] = None,
                 trust_certificates: pulumi.Input[Optional[_builtins.bool]] = None,
                 trust_fingerprints: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a Connection resource.

        :param pulumi.Input[_builtins.str] group_id: The unique identifier for the Group (Destination) within the Fivetran system.
        :param pulumi.Input[_builtins.str] service: The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). See [Fivetran connection types documentation](https://fivetran.com/docs/connectors) for available services.
        :param pulumi.Input[_builtins.str] config: Optional connection configuration as a JSON-encoded string. This config is merged with destination_schema fields and sent to the API during creation. The connection resource does not read this field back, allowing it to be managed separately by the `ConnectionConfig` resource. Use this to provide service-specific required fields (e.g., `update_method` for Postgres/MySQL) or full connection configuration.
        :param pulumi.Input[_builtins.str] data_delay_sensitivity: The level of data delay notification threshold. Possible values: LOW, NORMAL, HIGH, CUSTOM, SYNC_FREQUENCY. The default value NORMAL. CUSTOM is only available for customers using the [Enterprise plan](https://fivetran.com/docs/getting-started/pricing#fivetranplans) or above.
        :param pulumi.Input[_builtins.int] data_delay_threshold: Custom sync delay notification threshold in minutes. The default value is 0. This parameter is only used when data*delay*sensitivity set to CUSTOM.
        :param pulumi.Input[_builtins.str] hybrid_deployment_agent_id: The hybrid deployment agent ID that refers to the controller created for the group the connection belongs to. If the value is specified, the system will try to associate the connection with an existing agent.
        :param pulumi.Input[_builtins.str] networking_method: The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        :param pulumi.Input[_builtins.str] private_link_id: The private link ID. Required when `networking_method` is `PrivateLink`.
        :param pulumi.Input[_builtins.str] proxy_agent_id: The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        :param pulumi.Input[_builtins.bool] run_setup_tests: Whether to run setup tests when creating the connection. Default: `false`. **Note:** This is a plan-only attribute and will not be stored in state.
        :param pulumi.Input[_builtins.bool] trust_certificates: Specifies whether we should trust the certificate automatically. The default value is FALSE. If a certificate is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination certificate](https://fivetran.com/docs/rest-api/certificates#approveadestinationcertificate). **Note:** This is a plan-only attribute.
        :param pulumi.Input[_builtins.bool] trust_fingerprints: Specifies whether we should trust the SSH fingerprint automatically. The default value is FALSE. If a fingerprint is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination fingerprint](https://fivetran.com/docs/rest-api/certificates#approveadestinationfingerprint). **Note:** This is a plan-only attribute.
        """
        pulumi.set(__self__, "group_id", group_id)
        pulumi.set(__self__, "service", service)
        if config is not None:
            pulumi.set(__self__, "config", config)
        if data_delay_sensitivity is not None:
            pulumi.set(__self__, "data_delay_sensitivity", data_delay_sensitivity)
        if data_delay_threshold is not None:
            pulumi.set(__self__, "data_delay_threshold", data_delay_threshold)
        if destination_schema is not None:
            pulumi.set(__self__, "destination_schema", destination_schema)
        if hybrid_deployment_agent_id is not None:
            pulumi.set(__self__, "hybrid_deployment_agent_id", hybrid_deployment_agent_id)
        if networking_method is not None:
            pulumi.set(__self__, "networking_method", networking_method)
        if private_link_id is not None:
            pulumi.set(__self__, "private_link_id", private_link_id)
        if proxy_agent_id is not None:
            pulumi.set(__self__, "proxy_agent_id", proxy_agent_id)
        if run_setup_tests is not None:
            pulumi.set(__self__, "run_setup_tests", run_setup_tests)
        if trust_certificates is not None:
            pulumi.set(__self__, "trust_certificates", trust_certificates)
        if trust_fingerprints is not None:
            pulumi.set(__self__, "trust_fingerprints", trust_fingerprints)

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> pulumi.Input[_builtins.str]:
        """
        The unique identifier for the Group (Destination) within the Fivetran system.
        """
        return pulumi.get(self, "group_id")

    @group_id.setter
    def group_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "group_id", value)

    @_builtins.property
    @pulumi.getter
    def service(self) -> pulumi.Input[_builtins.str]:
        """
        The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). See [Fivetran connection types documentation](https://fivetran.com/docs/connectors) for available services.
        """
        return pulumi.get(self, "service")

    @service.setter
    def service(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "service", value)

    @_builtins.property
    @pulumi.getter
    def config(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional connection configuration as a JSON-encoded string. This config is merged with destination_schema fields and sent to the API during creation. The connection resource does not read this field back, allowing it to be managed separately by the `ConnectionConfig` resource. Use this to provide service-specific required fields (e.g., `update_method` for Postgres/MySQL) or full connection configuration.
        """
        return pulumi.get(self, "config")

    @config.setter
    def config(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "config", value)

    @_builtins.property
    @pulumi.getter(name="dataDelaySensitivity")
    def data_delay_sensitivity(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The level of data delay notification threshold. Possible values: LOW, NORMAL, HIGH, CUSTOM, SYNC_FREQUENCY. The default value NORMAL. CUSTOM is only available for customers using the [Enterprise plan](https://fivetran.com/docs/getting-started/pricing#fivetranplans) or above.
        """
        return pulumi.get(self, "data_delay_sensitivity")

    @data_delay_sensitivity.setter
    def data_delay_sensitivity(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "data_delay_sensitivity", value)

    @_builtins.property
    @pulumi.getter(name="dataDelayThreshold")
    def data_delay_threshold(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Custom sync delay notification threshold in minutes. The default value is 0. This parameter is only used when data*delay*sensitivity set to CUSTOM.
        """
        return pulumi.get(self, "data_delay_threshold")

    @data_delay_threshold.setter
    def data_delay_threshold(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "data_delay_threshold", value)

    @_builtins.property
    @pulumi.getter(name="destinationSchema")
    def destination_schema(self) -> pulumi.Input[Optional['ConnectionDestinationSchemaArgs']]:
        return pulumi.get(self, "destination_schema")

    @destination_schema.setter
    def destination_schema(self, value: pulumi.Input[Optional['ConnectionDestinationSchemaArgs']]):
        pulumi.set(self, "destination_schema", value)

    @_builtins.property
    @pulumi.getter(name="hybridDeploymentAgentId")
    def hybrid_deployment_agent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The hybrid deployment agent ID that refers to the controller created for the group the connection belongs to. If the value is specified, the system will try to associate the connection with an existing agent.
        """
        return pulumi.get(self, "hybrid_deployment_agent_id")

    @hybrid_deployment_agent_id.setter
    def hybrid_deployment_agent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "hybrid_deployment_agent_id", value)

    @_builtins.property
    @pulumi.getter(name="networkingMethod")
    def networking_method(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        """
        return pulumi.get(self, "networking_method")

    @networking_method.setter
    def networking_method(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "networking_method", value)

    @_builtins.property
    @pulumi.getter(name="privateLinkId")
    def private_link_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The private link ID. Required when `networking_method` is `PrivateLink`.
        """
        return pulumi.get(self, "private_link_id")

    @private_link_id.setter
    def private_link_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "private_link_id", value)

    @_builtins.property
    @pulumi.getter(name="proxyAgentId")
    def proxy_agent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        """
        return pulumi.get(self, "proxy_agent_id")

    @proxy_agent_id.setter
    def proxy_agent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "proxy_agent_id", value)

    @_builtins.property
    @pulumi.getter(name="runSetupTests")
    def run_setup_tests(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to run setup tests when creating the connection. Default: `false`. **Note:** This is a plan-only attribute and will not be stored in state.
        """
        return pulumi.get(self, "run_setup_tests")

    @run_setup_tests.setter
    def run_setup_tests(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "run_setup_tests", value)

    @_builtins.property
    @pulumi.getter(name="trustCertificates")
    def trust_certificates(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Specifies whether we should trust the certificate automatically. The default value is FALSE. If a certificate is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination certificate](https://fivetran.com/docs/rest-api/certificates#approveadestinationcertificate). **Note:** This is a plan-only attribute.
        """
        return pulumi.get(self, "trust_certificates")

    @trust_certificates.setter
    def trust_certificates(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "trust_certificates", value)

    @_builtins.property
    @pulumi.getter(name="trustFingerprints")
    def trust_fingerprints(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Specifies whether we should trust the SSH fingerprint automatically. The default value is FALSE. If a fingerprint is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination fingerprint](https://fivetran.com/docs/rest-api/certificates#approveadestinationfingerprint). **Note:** This is a plan-only attribute.
        """
        return pulumi.get(self, "trust_fingerprints")

    @trust_fingerprints.setter
    def trust_fingerprints(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "trust_fingerprints", value)


@pulumi.input_type
class _ConnectionState:
    def __init__(__self__, *,
                 config: pulumi.Input[Optional[_builtins.str]] = None,
                 connected_by: pulumi.Input[Optional[_builtins.str]] = None,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_sensitivity: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_threshold: pulumi.Input[Optional[_builtins.int]] = None,
                 destination_schema: pulumi.Input[Optional['ConnectionDestinationSchemaArgs']] = None,
                 group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 hybrid_deployment_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 networking_method: pulumi.Input[Optional[_builtins.str]] = None,
                 private_link_id: pulumi.Input[Optional[_builtins.str]] = None,
                 proxy_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 run_setup_tests: pulumi.Input[Optional[_builtins.bool]] = None,
                 service: pulumi.Input[Optional[_builtins.str]] = None,
                 trust_certificates: pulumi.Input[Optional[_builtins.bool]] = None,
                 trust_fingerprints: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering Connection resources.

        :param pulumi.Input[_builtins.str] config: Optional connection configuration as a JSON-encoded string. This config is merged with destination_schema fields and sent to the API during creation. The connection resource does not read this field back, allowing it to be managed separately by the `ConnectionConfig` resource. Use this to provide service-specific required fields (e.g., `update_method` for Postgres/MySQL) or full connection configuration.
        :param pulumi.Input[_builtins.str] connected_by: The unique identifier of the user who has created the connection in your account.
        :param pulumi.Input[_builtins.str] created_at: The timestamp of the time the connection was created in your account.
        :param pulumi.Input[_builtins.str] data_delay_sensitivity: The level of data delay notification threshold. Possible values: LOW, NORMAL, HIGH, CUSTOM, SYNC_FREQUENCY. The default value NORMAL. CUSTOM is only available for customers using the [Enterprise plan](https://fivetran.com/docs/getting-started/pricing#fivetranplans) or above.
        :param pulumi.Input[_builtins.int] data_delay_threshold: Custom sync delay notification threshold in minutes. The default value is 0. This parameter is only used when data*delay*sensitivity set to CUSTOM.
        :param pulumi.Input[_builtins.str] group_id: The unique identifier for the Group (Destination) within the Fivetran system.
        :param pulumi.Input[_builtins.str] hybrid_deployment_agent_id: The hybrid deployment agent ID that refers to the controller created for the group the connection belongs to. If the value is specified, the system will try to associate the connection with an existing agent.
        :param pulumi.Input[_builtins.str] name: The name used both as the connection's name within the Fivetran system and as the source schema's name within your destination.
        :param pulumi.Input[_builtins.str] networking_method: The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        :param pulumi.Input[_builtins.str] private_link_id: The private link ID. Required when `networking_method` is `PrivateLink`.
        :param pulumi.Input[_builtins.str] proxy_agent_id: The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        :param pulumi.Input[_builtins.bool] run_setup_tests: Whether to run setup tests when creating the connection. Default: `false`. **Note:** This is a plan-only attribute and will not be stored in state.
        :param pulumi.Input[_builtins.str] service: The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). See [Fivetran connection types documentation](https://fivetran.com/docs/connectors) for available services.
        :param pulumi.Input[_builtins.bool] trust_certificates: Specifies whether we should trust the certificate automatically. The default value is FALSE. If a certificate is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination certificate](https://fivetran.com/docs/rest-api/certificates#approveadestinationcertificate). **Note:** This is a plan-only attribute.
        :param pulumi.Input[_builtins.bool] trust_fingerprints: Specifies whether we should trust the SSH fingerprint automatically. The default value is FALSE. If a fingerprint is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination fingerprint](https://fivetran.com/docs/rest-api/certificates#approveadestinationfingerprint). **Note:** This is a plan-only attribute.
        """
        if config is not None:
            pulumi.set(__self__, "config", config)
        if connected_by is not None:
            pulumi.set(__self__, "connected_by", connected_by)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if data_delay_sensitivity is not None:
            pulumi.set(__self__, "data_delay_sensitivity", data_delay_sensitivity)
        if data_delay_threshold is not None:
            pulumi.set(__self__, "data_delay_threshold", data_delay_threshold)
        if destination_schema is not None:
            pulumi.set(__self__, "destination_schema", destination_schema)
        if group_id is not None:
            pulumi.set(__self__, "group_id", group_id)
        if hybrid_deployment_agent_id is not None:
            pulumi.set(__self__, "hybrid_deployment_agent_id", hybrid_deployment_agent_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if networking_method is not None:
            pulumi.set(__self__, "networking_method", networking_method)
        if private_link_id is not None:
            pulumi.set(__self__, "private_link_id", private_link_id)
        if proxy_agent_id is not None:
            pulumi.set(__self__, "proxy_agent_id", proxy_agent_id)
        if run_setup_tests is not None:
            pulumi.set(__self__, "run_setup_tests", run_setup_tests)
        if service is not None:
            pulumi.set(__self__, "service", service)
        if trust_certificates is not None:
            pulumi.set(__self__, "trust_certificates", trust_certificates)
        if trust_fingerprints is not None:
            pulumi.set(__self__, "trust_fingerprints", trust_fingerprints)

    @_builtins.property
    @pulumi.getter
    def config(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional connection configuration as a JSON-encoded string. This config is merged with destination_schema fields and sent to the API during creation. The connection resource does not read this field back, allowing it to be managed separately by the `ConnectionConfig` resource. Use this to provide service-specific required fields (e.g., `update_method` for Postgres/MySQL) or full connection configuration.
        """
        return pulumi.get(self, "config")

    @config.setter
    def config(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "config", value)

    @_builtins.property
    @pulumi.getter(name="connectedBy")
    def connected_by(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The unique identifier of the user who has created the connection in your account.
        """
        return pulumi.get(self, "connected_by")

    @connected_by.setter
    def connected_by(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "connected_by", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The timestamp of the time the connection was created in your account.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="dataDelaySensitivity")
    def data_delay_sensitivity(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The level of data delay notification threshold. Possible values: LOW, NORMAL, HIGH, CUSTOM, SYNC_FREQUENCY. The default value NORMAL. CUSTOM is only available for customers using the [Enterprise plan](https://fivetran.com/docs/getting-started/pricing#fivetranplans) or above.
        """
        return pulumi.get(self, "data_delay_sensitivity")

    @data_delay_sensitivity.setter
    def data_delay_sensitivity(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "data_delay_sensitivity", value)

    @_builtins.property
    @pulumi.getter(name="dataDelayThreshold")
    def data_delay_threshold(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Custom sync delay notification threshold in minutes. The default value is 0. This parameter is only used when data*delay*sensitivity set to CUSTOM.
        """
        return pulumi.get(self, "data_delay_threshold")

    @data_delay_threshold.setter
    def data_delay_threshold(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "data_delay_threshold", value)

    @_builtins.property
    @pulumi.getter(name="destinationSchema")
    def destination_schema(self) -> pulumi.Input[Optional['ConnectionDestinationSchemaArgs']]:
        return pulumi.get(self, "destination_schema")

    @destination_schema.setter
    def destination_schema(self, value: pulumi.Input[Optional['ConnectionDestinationSchemaArgs']]):
        pulumi.set(self, "destination_schema", value)

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The unique identifier for the Group (Destination) within the Fivetran system.
        """
        return pulumi.get(self, "group_id")

    @group_id.setter
    def group_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "group_id", value)

    @_builtins.property
    @pulumi.getter(name="hybridDeploymentAgentId")
    def hybrid_deployment_agent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The hybrid deployment agent ID that refers to the controller created for the group the connection belongs to. If the value is specified, the system will try to associate the connection with an existing agent.
        """
        return pulumi.get(self, "hybrid_deployment_agent_id")

    @hybrid_deployment_agent_id.setter
    def hybrid_deployment_agent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "hybrid_deployment_agent_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name used both as the connection's name within the Fivetran system and as the source schema's name within your destination.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="networkingMethod")
    def networking_method(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        """
        return pulumi.get(self, "networking_method")

    @networking_method.setter
    def networking_method(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "networking_method", value)

    @_builtins.property
    @pulumi.getter(name="privateLinkId")
    def private_link_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The private link ID. Required when `networking_method` is `PrivateLink`.
        """
        return pulumi.get(self, "private_link_id")

    @private_link_id.setter
    def private_link_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "private_link_id", value)

    @_builtins.property
    @pulumi.getter(name="proxyAgentId")
    def proxy_agent_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        """
        return pulumi.get(self, "proxy_agent_id")

    @proxy_agent_id.setter
    def proxy_agent_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "proxy_agent_id", value)

    @_builtins.property
    @pulumi.getter(name="runSetupTests")
    def run_setup_tests(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to run setup tests when creating the connection. Default: `false`. **Note:** This is a plan-only attribute and will not be stored in state.
        """
        return pulumi.get(self, "run_setup_tests")

    @run_setup_tests.setter
    def run_setup_tests(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "run_setup_tests", value)

    @_builtins.property
    @pulumi.getter
    def service(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). See [Fivetran connection types documentation](https://fivetran.com/docs/connectors) for available services.
        """
        return pulumi.get(self, "service")

    @service.setter
    def service(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "service", value)

    @_builtins.property
    @pulumi.getter(name="trustCertificates")
    def trust_certificates(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Specifies whether we should trust the certificate automatically. The default value is FALSE. If a certificate is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination certificate](https://fivetran.com/docs/rest-api/certificates#approveadestinationcertificate). **Note:** This is a plan-only attribute.
        """
        return pulumi.get(self, "trust_certificates")

    @trust_certificates.setter
    def trust_certificates(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "trust_certificates", value)

    @_builtins.property
    @pulumi.getter(name="trustFingerprints")
    def trust_fingerprints(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Specifies whether we should trust the SSH fingerprint automatically. The default value is FALSE. If a fingerprint is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination fingerprint](https://fivetran.com/docs/rest-api/certificates#approveadestinationfingerprint). **Note:** This is a plan-only attribute.
        """
        return pulumi.get(self, "trust_fingerprints")

    @trust_fingerprints.setter
    def trust_fingerprints(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "trust_fingerprints", value)


@pulumi.type_token("fivetran:index/connection:Connection")
class Connection(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 config: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_sensitivity: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_threshold: pulumi.Input[Optional[_builtins.int]] = None,
                 destination_schema: pulumi.Input[Optional[Union['ConnectionDestinationSchemaArgs', 'ConnectionDestinationSchemaArgsDict']]] = None,
                 group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 hybrid_deployment_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 networking_method: pulumi.Input[Optional[_builtins.str]] = None,
                 private_link_id: pulumi.Input[Optional[_builtins.str]] = None,
                 proxy_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 run_setup_tests: pulumi.Input[Optional[_builtins.bool]] = None,
                 service: pulumi.Input[Optional[_builtins.str]] = None,
                 trust_certificates: pulumi.Input[Optional[_builtins.bool]] = None,
                 trust_fingerprints: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        This resource allows you to create, update, and delete connections in Fivetran using JSON-based configuration.

        The `Connection` resource creates a connection with basic metadata (service type, destination schema, networking options). To configure connection details like host, port, credentials, use the `ConnectionConfig` resource.

        ## Example Usage

        ### Basic PostgreSQL Connection with Minimal Config

        ```python
        import pulumi
        import json
        import pulumi_provider_fivetran as fivetran

        example = fivetran.Group("example", name="My Destination")
        postgres = fivetran.Connection("postgres",
            group_id=example.id,
            service="postgres",
            destination_schema={
                "prefix": "my_postgres",
            },
            config=json.dumps({
                "update_method": "XMIN",
            }),
            run_setup_tests=False,
            trust_certificates=False,
            trust_fingerprints=False)
        ```

        ### PostgreSQL Connection with Full Configuration

        ```python
        import pulumi
        import json
        import pulumi_provider_fivetran as fivetran

        postgres_full = fivetran.Connection("postgres_full",
            group_id=example["id"],
            service="postgres",
            destination_schema={
                "prefix": "my_postgres",
            },
            config=json.dumps({
                "update_method": "XMIN",
                "host": database_config["host"],
                "port": 5432,
                "database": "mydb",
                "user": "fivetran_user",
            }),
            run_setup_tests=False)
        ```

        ### MySQL Connection with Proxy Agent

        ```python
        import pulumi
        import pulumi_provider_fivetran as fivetran

        example = fivetran.ProxyAgent("example",
            display_name="My Proxy Agent",
            group_region="GCP_US_EAST4")
        mysql = fivetran.Connection("mysql",
            group_id=example_fivetran_group["id"],
            service="mysql",
            destination_schema={
                "prefix": "my_mysql",
            },
            networking_method="ProxyAgent",
            proxy_agent_id=example.id,
            run_setup_tests=False)
        ```

        ### S3 Connection with Custom Schema Name

        ```python
        import pulumi
        import pulumi_provider_fivetran as fivetran

        s3 = fivetran.Connection("s3",
            group_id=example["id"],
            service="s3",
            destination_schema={
                "name": "s3_data_schema",
            },
            run_setup_tests=False)
        ```

        ### Connection with Data Delay Settings

        ```python
        import pulumi
        import pulumi_provider_fivetran as fivetran

        snowflake_connection = fivetran.Connection("snowflake_connection",
            group_id=example["id"],
            service="snowflake",
            destination_schema={
                "prefix": "snowflake_data",
            },
            data_delay_sensitivity="HIGH",
            data_delay_threshold=30,
            run_setup_tests=False)
        ```

        ## Notes

        - **Configuration Details:** This resource creates the connection structure. To configure connection-specific details (host, port, credentials, etc.), use the `ConnectionConfig` resource.
        - **Setup Tests:** When `run_setup_tests` is `true`, Fivetran will validate the connection configuration. Any test failures will appear as warnings in the Terraform output.
        - **Paused State:** Connections are created in a paused state by default. Use the connection schedule resource or the Fivetran UI to unpause the connection.
        - **Service Types:** See the [Fivetran documentation](https://fivetran.com/docs/connectors) for the complete list of available connection services.

        ## See Also

        - `ConnectionConfig` - Configure connection details (host, credentials, etc.)
        - `ConnectorSchedule` - Manage connection sync schedules
        - `fivetran_connector_schema` - Manage connection schema settings

        ## Import

        Connections can be imported using the connection ID:

        ```sh
        $ pulumi import fivetran:index/connection:Connection example connection_id_here
        ```

        **Note:** When importing, the `run_setup_tests`, `trust_certificates`, and `trust_fingerprints` attributes will not be imported as they are plan-only attributes.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] config: Optional connection configuration as a JSON-encoded string. This config is merged with destination_schema fields and sent to the API during creation. The connection resource does not read this field back, allowing it to be managed separately by the `ConnectionConfig` resource. Use this to provide service-specific required fields (e.g., `update_method` for Postgres/MySQL) or full connection configuration.
        :param pulumi.Input[_builtins.str] data_delay_sensitivity: The level of data delay notification threshold. Possible values: LOW, NORMAL, HIGH, CUSTOM, SYNC_FREQUENCY. The default value NORMAL. CUSTOM is only available for customers using the [Enterprise plan](https://fivetran.com/docs/getting-started/pricing#fivetranplans) or above.
        :param pulumi.Input[_builtins.int] data_delay_threshold: Custom sync delay notification threshold in minutes. The default value is 0. This parameter is only used when data*delay*sensitivity set to CUSTOM.
        :param pulumi.Input[_builtins.str] group_id: The unique identifier for the Group (Destination) within the Fivetran system.
        :param pulumi.Input[_builtins.str] hybrid_deployment_agent_id: The hybrid deployment agent ID that refers to the controller created for the group the connection belongs to. If the value is specified, the system will try to associate the connection with an existing agent.
        :param pulumi.Input[_builtins.str] networking_method: The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        :param pulumi.Input[_builtins.str] private_link_id: The private link ID. Required when `networking_method` is `PrivateLink`.
        :param pulumi.Input[_builtins.str] proxy_agent_id: The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        :param pulumi.Input[_builtins.bool] run_setup_tests: Whether to run setup tests when creating the connection. Default: `false`. **Note:** This is a plan-only attribute and will not be stored in state.
        :param pulumi.Input[_builtins.str] service: The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). See [Fivetran connection types documentation](https://fivetran.com/docs/connectors) for available services.
        :param pulumi.Input[_builtins.bool] trust_certificates: Specifies whether we should trust the certificate automatically. The default value is FALSE. If a certificate is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination certificate](https://fivetran.com/docs/rest-api/certificates#approveadestinationcertificate). **Note:** This is a plan-only attribute.
        :param pulumi.Input[_builtins.bool] trust_fingerprints: Specifies whether we should trust the SSH fingerprint automatically. The default value is FALSE. If a fingerprint is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination fingerprint](https://fivetran.com/docs/rest-api/certificates#approveadestinationfingerprint). **Note:** This is a plan-only attribute.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ConnectionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        This resource allows you to create, update, and delete connections in Fivetran using JSON-based configuration.

        The `Connection` resource creates a connection with basic metadata (service type, destination schema, networking options). To configure connection details like host, port, credentials, use the `ConnectionConfig` resource.

        ## Example Usage

        ### Basic PostgreSQL Connection with Minimal Config

        ```python
        import pulumi
        import json
        import pulumi_provider_fivetran as fivetran

        example = fivetran.Group("example", name="My Destination")
        postgres = fivetran.Connection("postgres",
            group_id=example.id,
            service="postgres",
            destination_schema={
                "prefix": "my_postgres",
            },
            config=json.dumps({
                "update_method": "XMIN",
            }),
            run_setup_tests=False,
            trust_certificates=False,
            trust_fingerprints=False)
        ```

        ### PostgreSQL Connection with Full Configuration

        ```python
        import pulumi
        import json
        import pulumi_provider_fivetran as fivetran

        postgres_full = fivetran.Connection("postgres_full",
            group_id=example["id"],
            service="postgres",
            destination_schema={
                "prefix": "my_postgres",
            },
            config=json.dumps({
                "update_method": "XMIN",
                "host": database_config["host"],
                "port": 5432,
                "database": "mydb",
                "user": "fivetran_user",
            }),
            run_setup_tests=False)
        ```

        ### MySQL Connection with Proxy Agent

        ```python
        import pulumi
        import pulumi_provider_fivetran as fivetran

        example = fivetran.ProxyAgent("example",
            display_name="My Proxy Agent",
            group_region="GCP_US_EAST4")
        mysql = fivetran.Connection("mysql",
            group_id=example_fivetran_group["id"],
            service="mysql",
            destination_schema={
                "prefix": "my_mysql",
            },
            networking_method="ProxyAgent",
            proxy_agent_id=example.id,
            run_setup_tests=False)
        ```

        ### S3 Connection with Custom Schema Name

        ```python
        import pulumi
        import pulumi_provider_fivetran as fivetran

        s3 = fivetran.Connection("s3",
            group_id=example["id"],
            service="s3",
            destination_schema={
                "name": "s3_data_schema",
            },
            run_setup_tests=False)
        ```

        ### Connection with Data Delay Settings

        ```python
        import pulumi
        import pulumi_provider_fivetran as fivetran

        snowflake_connection = fivetran.Connection("snowflake_connection",
            group_id=example["id"],
            service="snowflake",
            destination_schema={
                "prefix": "snowflake_data",
            },
            data_delay_sensitivity="HIGH",
            data_delay_threshold=30,
            run_setup_tests=False)
        ```

        ## Notes

        - **Configuration Details:** This resource creates the connection structure. To configure connection-specific details (host, port, credentials, etc.), use the `ConnectionConfig` resource.
        - **Setup Tests:** When `run_setup_tests` is `true`, Fivetran will validate the connection configuration. Any test failures will appear as warnings in the Terraform output.
        - **Paused State:** Connections are created in a paused state by default. Use the connection schedule resource or the Fivetran UI to unpause the connection.
        - **Service Types:** See the [Fivetran documentation](https://fivetran.com/docs/connectors) for the complete list of available connection services.

        ## See Also

        - `ConnectionConfig` - Configure connection details (host, credentials, etc.)
        - `ConnectorSchedule` - Manage connection sync schedules
        - `fivetran_connector_schema` - Manage connection schema settings

        ## Import

        Connections can be imported using the connection ID:

        ```sh
        $ pulumi import fivetran:index/connection:Connection example connection_id_here
        ```

        **Note:** When importing, the `run_setup_tests`, `trust_certificates`, and `trust_fingerprints` attributes will not be imported as they are plan-only attributes.


        :param str resource_name: The name of the resource.
        :param ConnectionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ConnectionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 config: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_sensitivity: pulumi.Input[Optional[_builtins.str]] = None,
                 data_delay_threshold: pulumi.Input[Optional[_builtins.int]] = None,
                 destination_schema: pulumi.Input[Optional[Union['ConnectionDestinationSchemaArgs', 'ConnectionDestinationSchemaArgsDict']]] = None,
                 group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 hybrid_deployment_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 networking_method: pulumi.Input[Optional[_builtins.str]] = None,
                 private_link_id: pulumi.Input[Optional[_builtins.str]] = None,
                 proxy_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
                 run_setup_tests: pulumi.Input[Optional[_builtins.bool]] = None,
                 service: pulumi.Input[Optional[_builtins.str]] = None,
                 trust_certificates: pulumi.Input[Optional[_builtins.bool]] = None,
                 trust_fingerprints: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ConnectionArgs.__new__(ConnectionArgs)

            __props__.__dict__["config"] = config
            __props__.__dict__["data_delay_sensitivity"] = data_delay_sensitivity
            __props__.__dict__["data_delay_threshold"] = data_delay_threshold
            __props__.__dict__["destination_schema"] = destination_schema
            if group_id is None and not opts.urn:
                raise TypeError("Missing required property 'group_id'")
            __props__.__dict__["group_id"] = group_id
            __props__.__dict__["hybrid_deployment_agent_id"] = hybrid_deployment_agent_id
            __props__.__dict__["networking_method"] = networking_method
            __props__.__dict__["private_link_id"] = private_link_id
            __props__.__dict__["proxy_agent_id"] = proxy_agent_id
            __props__.__dict__["run_setup_tests"] = run_setup_tests
            if service is None and not opts.urn:
                raise TypeError("Missing required property 'service'")
            __props__.__dict__["service"] = service
            __props__.__dict__["trust_certificates"] = trust_certificates
            __props__.__dict__["trust_fingerprints"] = trust_fingerprints
            __props__.__dict__["connected_by"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["name"] = None
        super(Connection, __self__).__init__(
            'fivetran:index/connection:Connection',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            config: pulumi.Input[Optional[_builtins.str]] = None,
            connected_by: pulumi.Input[Optional[_builtins.str]] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            data_delay_sensitivity: pulumi.Input[Optional[_builtins.str]] = None,
            data_delay_threshold: pulumi.Input[Optional[_builtins.int]] = None,
            destination_schema: pulumi.Input[Optional[Union['ConnectionDestinationSchemaArgs', 'ConnectionDestinationSchemaArgsDict']]] = None,
            group_id: pulumi.Input[Optional[_builtins.str]] = None,
            hybrid_deployment_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            networking_method: pulumi.Input[Optional[_builtins.str]] = None,
            private_link_id: pulumi.Input[Optional[_builtins.str]] = None,
            proxy_agent_id: pulumi.Input[Optional[_builtins.str]] = None,
            run_setup_tests: pulumi.Input[Optional[_builtins.bool]] = None,
            service: pulumi.Input[Optional[_builtins.str]] = None,
            trust_certificates: pulumi.Input[Optional[_builtins.bool]] = None,
            trust_fingerprints: pulumi.Input[Optional[_builtins.bool]] = None) -> 'Connection':
        """
        Get an existing Connection resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] config: Optional connection configuration as a JSON-encoded string. This config is merged with destination_schema fields and sent to the API during creation. The connection resource does not read this field back, allowing it to be managed separately by the `ConnectionConfig` resource. Use this to provide service-specific required fields (e.g., `update_method` for Postgres/MySQL) or full connection configuration.
        :param pulumi.Input[_builtins.str] connected_by: The unique identifier of the user who has created the connection in your account.
        :param pulumi.Input[_builtins.str] created_at: The timestamp of the time the connection was created in your account.
        :param pulumi.Input[_builtins.str] data_delay_sensitivity: The level of data delay notification threshold. Possible values: LOW, NORMAL, HIGH, CUSTOM, SYNC_FREQUENCY. The default value NORMAL. CUSTOM is only available for customers using the [Enterprise plan](https://fivetran.com/docs/getting-started/pricing#fivetranplans) or above.
        :param pulumi.Input[_builtins.int] data_delay_threshold: Custom sync delay notification threshold in minutes. The default value is 0. This parameter is only used when data*delay*sensitivity set to CUSTOM.
        :param pulumi.Input[_builtins.str] group_id: The unique identifier for the Group (Destination) within the Fivetran system.
        :param pulumi.Input[_builtins.str] hybrid_deployment_agent_id: The hybrid deployment agent ID that refers to the controller created for the group the connection belongs to. If the value is specified, the system will try to associate the connection with an existing agent.
        :param pulumi.Input[_builtins.str] name: The name used both as the connection's name within the Fivetran system and as the source schema's name within your destination.
        :param pulumi.Input[_builtins.str] networking_method: The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        :param pulumi.Input[_builtins.str] private_link_id: The private link ID. Required when `networking_method` is `PrivateLink`.
        :param pulumi.Input[_builtins.str] proxy_agent_id: The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        :param pulumi.Input[_builtins.bool] run_setup_tests: Whether to run setup tests when creating the connection. Default: `false`. **Note:** This is a plan-only attribute and will not be stored in state.
        :param pulumi.Input[_builtins.str] service: The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). See [Fivetran connection types documentation](https://fivetran.com/docs/connectors) for available services.
        :param pulumi.Input[_builtins.bool] trust_certificates: Specifies whether we should trust the certificate automatically. The default value is FALSE. If a certificate is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination certificate](https://fivetran.com/docs/rest-api/certificates#approveadestinationcertificate). **Note:** This is a plan-only attribute.
        :param pulumi.Input[_builtins.bool] trust_fingerprints: Specifies whether we should trust the SSH fingerprint automatically. The default value is FALSE. If a fingerprint is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination fingerprint](https://fivetran.com/docs/rest-api/certificates#approveadestinationfingerprint). **Note:** This is a plan-only attribute.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ConnectionState.__new__(_ConnectionState)

        __props__.__dict__["config"] = config
        __props__.__dict__["connected_by"] = connected_by
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["data_delay_sensitivity"] = data_delay_sensitivity
        __props__.__dict__["data_delay_threshold"] = data_delay_threshold
        __props__.__dict__["destination_schema"] = destination_schema
        __props__.__dict__["group_id"] = group_id
        __props__.__dict__["hybrid_deployment_agent_id"] = hybrid_deployment_agent_id
        __props__.__dict__["name"] = name
        __props__.__dict__["networking_method"] = networking_method
        __props__.__dict__["private_link_id"] = private_link_id
        __props__.__dict__["proxy_agent_id"] = proxy_agent_id
        __props__.__dict__["run_setup_tests"] = run_setup_tests
        __props__.__dict__["service"] = service
        __props__.__dict__["trust_certificates"] = trust_certificates
        __props__.__dict__["trust_fingerprints"] = trust_fingerprints
        return Connection(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def config(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional connection configuration as a JSON-encoded string. This config is merged with destination_schema fields and sent to the API during creation. The connection resource does not read this field back, allowing it to be managed separately by the `ConnectionConfig` resource. Use this to provide service-specific required fields (e.g., `update_method` for Postgres/MySQL) or full connection configuration.
        """
        return pulumi.get(self, "config")

    @_builtins.property
    @pulumi.getter(name="connectedBy")
    def connected_by(self) -> pulumi.Output[_builtins.str]:
        """
        The unique identifier of the user who has created the connection in your account.
        """
        return pulumi.get(self, "connected_by")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        The timestamp of the time the connection was created in your account.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="dataDelaySensitivity")
    def data_delay_sensitivity(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The level of data delay notification threshold. Possible values: LOW, NORMAL, HIGH, CUSTOM, SYNC_FREQUENCY. The default value NORMAL. CUSTOM is only available for customers using the [Enterprise plan](https://fivetran.com/docs/getting-started/pricing#fivetranplans) or above.
        """
        return pulumi.get(self, "data_delay_sensitivity")

    @_builtins.property
    @pulumi.getter(name="dataDelayThreshold")
    def data_delay_threshold(self) -> pulumi.Output[_builtins.int]:
        """
        Custom sync delay notification threshold in minutes. The default value is 0. This parameter is only used when data*delay*sensitivity set to CUSTOM.
        """
        return pulumi.get(self, "data_delay_threshold")

    @_builtins.property
    @pulumi.getter(name="destinationSchema")
    def destination_schema(self) -> pulumi.Output[Optional['outputs.ConnectionDestinationSchema']]:
        return pulumi.get(self, "destination_schema")

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> pulumi.Output[_builtins.str]:
        """
        The unique identifier for the Group (Destination) within the Fivetran system.
        """
        return pulumi.get(self, "group_id")

    @_builtins.property
    @pulumi.getter(name="hybridDeploymentAgentId")
    def hybrid_deployment_agent_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The hybrid deployment agent ID that refers to the controller created for the group the connection belongs to. If the value is specified, the system will try to associate the connection with an existing agent.
        """
        return pulumi.get(self, "hybrid_deployment_agent_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name used both as the connection's name within the Fivetran system and as the source schema's name within your destination.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="networkingMethod")
    def networking_method(self) -> pulumi.Output[_builtins.str]:
        """
        The networking method for the connection. Possible values: `Directly`, `SshTunnel`, `ProxyAgent`, `PrivateLink`.
        """
        return pulumi.get(self, "networking_method")

    @_builtins.property
    @pulumi.getter(name="privateLinkId")
    def private_link_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The private link ID. Required when `networking_method` is `PrivateLink`.
        """
        return pulumi.get(self, "private_link_id")

    @_builtins.property
    @pulumi.getter(name="proxyAgentId")
    def proxy_agent_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The ID of the proxy agent to use. Required when `networking_method` is `ProxyAgent`.
        """
        return pulumi.get(self, "proxy_agent_id")

    @_builtins.property
    @pulumi.getter(name="runSetupTests")
    def run_setup_tests(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether to run setup tests when creating the connection. Default: `false`. **Note:** This is a plan-only attribute and will not be stored in state.
        """
        return pulumi.get(self, "run_setup_tests")

    @_builtins.property
    @pulumi.getter
    def service(self) -> pulumi.Output[_builtins.str]:
        """
        The connection service type (e.g., `postgres`, `mysql`, `s3`, `snowflake`). See [Fivetran connection types documentation](https://fivetran.com/docs/connectors) for available services.
        """
        return pulumi.get(self, "service")

    @_builtins.property
    @pulumi.getter(name="trustCertificates")
    def trust_certificates(self) -> pulumi.Output[_builtins.bool]:
        """
        Specifies whether we should trust the certificate automatically. The default value is FALSE. If a certificate is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination certificate](https://fivetran.com/docs/rest-api/certificates#approveadestinationcertificate). **Note:** This is a plan-only attribute.
        """
        return pulumi.get(self, "trust_certificates")

    @_builtins.property
    @pulumi.getter(name="trustFingerprints")
    def trust_fingerprints(self) -> pulumi.Output[_builtins.bool]:
        """
        Specifies whether we should trust the SSH fingerprint automatically. The default value is FALSE. If a fingerprint is not trusted automatically, it has to be approved with [Certificates Management API Approve a destination fingerprint](https://fivetran.com/docs/rest-api/certificates#approveadestinationfingerprint). **Note:** This is a plan-only attribute.
        """
        return pulumi.get(self, "trust_fingerprints")

