# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetWebhooksResult',
    'AwaitableGetWebhooksResult',
    'get_webhooks',
    'get_webhooks_output',
]

@pulumi.output_type
class GetWebhooksResult:
    """
    A collection of values returned by getWebhooks.
    """
    def __init__(__self__, webhooks=None):
        if webhooks and not isinstance(webhooks, list):
            raise TypeError("Expected argument 'webhooks' to be a list")
        pulumi.set(__self__, "webhooks", webhooks)

    @_builtins.property
    @pulumi.getter
    def webhooks(self) -> Sequence['outputs.GetWebhooksWebhookResult']:
        return pulumi.get(self, "webhooks")


class AwaitableGetWebhooksResult(GetWebhooksResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetWebhooksResult(
            webhooks=self.webhooks)


def get_webhooks(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetWebhooksResult:
    """
    This data source returns a list of all webhooks within your Fivetran account.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_fivetran as fivetran

    webhooks = fivetran.get_webhooks()
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fivetran:index/getWebhooks:getWebhooks', __args__, opts=opts, typ=GetWebhooksResult).value

    return AwaitableGetWebhooksResult(
        webhooks=pulumi.get(__ret__, 'webhooks'))
def get_webhooks_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetWebhooksResult]:
    """
    This data source returns a list of all webhooks within your Fivetran account.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_fivetran as fivetran

    webhooks = fivetran.get_webhooks()
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fivetran:index/getWebhooks:getWebhooks', __args__, opts=opts, typ=GetWebhooksResult)
    return __ret__.apply(lambda __response__: GetWebhooksResult(
        webhooks=pulumi.get(__response__, 'webhooks')))
