// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Inputs
{

    public sealed class ConnectorConfigAppIdsAppsflyerGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Appsflyer`: Your App ID
        /// </summary>
        [Input("appId")]
        public Input<string>? AppId { get; set; }

        public ConnectorConfigAppIdsAppsflyerGetArgs()
        {
        }
        public static new ConnectorConfigAppIdsAppsflyerGetArgs Empty => new ConnectorConfigAppIdsAppsflyerGetArgs();
    }
}
