// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Inputs
{

    public sealed class ConnectorConfigAzureCredentialsArgs : global::Pulumi.ResourceArgs
    {
        [Input("connectionString")]
        private Input<string>? _connectionString;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Pendo`: Azure connection string
        /// </summary>
        public Input<string>? ConnectionString
        {
            get => _connectionString;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _connectionString = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Pendo`: Azure container name
        /// </summary>
        [Input("containerName")]
        public Input<string>? ContainerName { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Pendo`: Azure home folder
        /// </summary>
        [Input("homeFolder")]
        public Input<string>? HomeFolder { get; set; }

        public ConnectorConfigAzureCredentialsArgs()
        {
        }
        public static new ConnectorConfigAzureCredentialsArgs Empty => new ConnectorConfigAzureCredentialsArgs();
    }
}
