// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Inputs
{

    public sealed class ConnectorConfigCustomPayloadArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AwsLambda`: Payload Key
        /// 	- Service `AzureFunction`: Payload Key
        /// 	- Service `GoogleCloudFunction`: Payload Key
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AwsLambda`: Payload Value
        /// 	- Service `AzureFunction`: Payload Value
        /// 	- Service `GoogleCloudFunction`: Payload Value
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public ConnectorConfigCustomPayloadArgs()
        {
        }
        public static new ConnectorConfigCustomPayloadArgs Empty => new ConnectorConfigCustomPayloadArgs();
    }
}
