// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Inputs
{

    public sealed class ConnectorAuthArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessToken")]
        private Input<string>? _accessToken;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AmazonDsp`: Your Amazon DSP access token.
        /// 	- Service `AutodeskBim360`: Your Autodesk BIM 360 Access Token.
        /// 	- Service `AzureSqlDb`: The long-lived Access token carries the information necessary to access API resources.
        /// 	- Service `AzureSqlManagedDb`: The long-lived Access token carries the information necessary to access API resources.
        /// 	- Service `BillingPlatform`: Your BillingPlatform access token.
        /// 	- Service `Calendly`: Your Calendly access token.
        /// 	- Service `Docebo`: Your Docebo Access Token.
        /// 	- Service `Drift`: Your Drift access token.
        /// 	- Service `EmploymentHero`: Your Employment Hero access token.
        /// 	- Service `FacebookAds`: The long-lived `Access token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to query the Facebook Ads API. Use either `AccessToken` or `UserAccessToken`, not both at the same time.
        /// 	- Service `FacebookPages`: The `Access Token` carries the information necessary for API resources to fetch data
        /// 	- Service `Freshbooks`: Your FreshBooks Access Token.
        /// 	- Service `Gitlab`: Your GitLab access token.
        /// 	- Service `Gmail`: The `Access Token` that carries the information necessary for API resources to fetch data.
        /// 	- Service `GoogleBusinessProfile`: Your Google Business Profile Access token.
        /// 	- Service `GoogleCalendar`: Your Google Calendar access token.
        /// 	- Service `GoogleClassroom`: The `Access Token` that carries the information necessary for API resources to fetch data.
        /// 	- Service `GoogleTagManager`: Your Google Tag Manager access token.
        /// 	- Service `GoogleTasks`: The access token that carries the information necessary for API resources to your Google Tasks fetch data.
        /// 	- Service `InstagramBusiness`: The `Access Token` carries the information necessary for API resources to fetch data
        /// 	- Service `Intercom`: The long-lived `Access Token` carries the information necessary for API resources to fetch data.
        /// 	- Service `LightspeedRetailXseries`: Your Lightspeed Retail X-Series access token.
        /// 	- Service `Medallia`: Your Medallia access token that contains all the information necessary for the API resources to fetch your data.
        /// 	- Service `PinterestOrganic`: Your Pinterest access token.
        /// 	- Service `Ramp`: Your Ramp access token.
        /// 	- Service `Ringcentral`: The long-lived `Access token` carries the information necessary to access API resources.
        /// 	- Service `Shopify`: The Shopify access token.
        /// 	- Service `Slack`: Your Slack access token.
        /// 	- Service `Stripe`: The Stripe API Restricted Key
        /// 	- Service `StripeTest`: The Stripe API Restricted Key
        /// 	- Service `SurveyMonkey`: The long-lived `Access token` carries the information necessary to access API resources.
        /// 	- Service `TiktokAds`: The long-lived `Access token` carries the information necessary to access API resources.
        /// 	- Service `TiktokOrganicApp`: Your TikTok Organic access token.
        /// 	- Service `Tremendous`: Your Tremendous access token.
        /// 	- Service `Typeform`: The Typeform API access token.
        /// 	- Service `YahooSearchAdsYahooJapan`: Your Yahoo Search Ads Access Token.
        /// 	- Service `Zendesk`: The long-lived `Access token` carries the information necessary to access API resources.
        /// 	- Service `ZendeskChat`: The long-lived `Access token` carries the information necessary to access API resources.
        /// 	- Service `ZendeskSell`: The long-lived `Access token` carries the information necessary to access API resources.
        /// 	- Service `Zoom`: Your Zoom Access token.
        /// </summary>
        public Input<string>? AccessToken
        {
            get => _accessToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accessToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `ElasticCloud`: The Elasticsearch API key. If omitted, then basic user and password authentication will apply.
        /// 	- Service `EsSelfHosted`: The Elasticsearch API key. If omitted, then basic user and password authentication will apply.
        /// </summary>
        [Input("apiKey")]
        public Input<string>? ApiKey { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AmazonSellingPartner`: `Application ID` of the public application registered in the Amazon Selling Partner Appstore that you want to use for authentication of your connection. Use this parameter along with `Client ID` and `Client Secret` only if you want to use your own public application for authorisation via Connect Card.
        /// </summary>
        [Input("applicationId")]
        public Input<string>? ApplicationId { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GooglePlay`: Authentication Method
        /// </summary>
        [Input("authenticationMethod")]
        public Input<string>? AuthenticationMethod { get; set; }

        [Input("clientAccess")]
        public Input<Inputs.ConnectorAuthClientAccessArgs>? ClientAccess { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AmazonSellingPartner`: `Client ID` of your Amazon Seller/Vendor Central client application.
        /// 	- Service `AppleSearchAds`: Apple Search Ads REST API Client ID. Must be populated if `IsAuth2Enabled` is set to `True`.
        /// 	- Service `AzureBlobStorage`: `Client ID` of your Microsoft client application.
        /// 	- Service `MicrosoftDynamics365Fno`: `Client ID` of your Microsoft client application.
        /// 	- Service `Workday`: Client ID
        /// 	- Service `WorkdayFinancialManagement`: ID of your Workday Client App
        /// 	- Service `WorkdayHcm`: ID of your Workday Client App
        /// 	- Service `YahooDsp`: Your Yahoo DSP Client ID.
        /// </summary>
        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        [Input("clientSecret")]
        private Input<string>? _clientSecret;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AmazonSellingPartner`: `Client Secret` of your Amazon Seller/Vendor Central client application.
        /// 	- Service `AzureBlobStorage`: `Client Secret` of your Microsoft client application.
        /// 	- Service `MicrosoftDynamics365Fno`: `Client Secret` of your Microsoft client application.
        /// 	- Service `Workday`: Client Secret
        /// 	- Service `WorkdayFinancialManagement`: Secret of your Workday Client App
        /// 	- Service `WorkdayHcm`: Secret of your Workday Client App
        /// 	- Service `YahooDsp`: Your Yahoo DSP Client Secret.
        /// </summary>
        public Input<string>? ClientSecret
        {
            get => _clientSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Twitter`: API Key of your app
        /// 	- Service `TwitterAds`: The X App consumer key.
        /// </summary>
        [Input("consumerKey")]
        public Input<string>? ConsumerKey { get; set; }

        [Input("consumerSecret")]
        private Input<string>? _consumerSecret;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Twitter`: API Secret of your app
        /// 	- Service `TwitterAds`: The X App consumer secret.
        /// </summary>
        public Input<string>? ConsumerSecret
        {
            get => _consumerSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _consumerSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `ConfluentCloud`: Optional Confluent Cloud identity pool ID. When omitted, Confluent auto-maps the token to a matching pool.
        /// </summary>
        [Input("identityPoolId")]
        public Input<string>? IdentityPoolId { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AppleSearchAds`: Apple Search Ads REST API Key ID. Must be populated if `IsAuth2Enabled` is set to `True`.
        /// </summary>
        [Input("keyId")]
        public Input<string>? KeyId { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `ConfluentCloud`: Confluent Cloud logical cluster ID. Required for OAuth 2.0 authentication.
        /// </summary>
        [Input("logicalClusterId")]
        public Input<string>? LogicalClusterId { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AzureSqlDb`: User Assigned Managed Identity Client ID.
        /// 	- Service `AzureSqlManagedDb`: User Assigned Managed Identity Client ID.
        /// </summary>
        [Input("managedIdentityUserAssigned")]
        public Input<string>? ManagedIdentityUserAssigned { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `ConfluentCloud`: OAuth 2.0 client ID issued by the identity provider.
        /// </summary>
        [Input("oauthClientId")]
        public Input<string>? OauthClientId { get; set; }

        [Input("oauthClientSecret")]
        private Input<string>? _oauthClientSecret;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `ConfluentCloud`: OAuth 2.0 client secret issued by the identity provider.
        /// </summary>
        public Input<string>? OauthClientSecret
        {
            get => _oauthClientSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _oauthClientSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `ConfluentCloud`: Optional OAuth 2.0 scope to request with the access token.
        /// </summary>
        [Input("oauthScope")]
        public Input<string>? OauthScope { get; set; }

        [Input("oauthToken")]
        private Input<string>? _oauthToken;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Twitter`: The X App access token.
        /// 	- Service `TwitterAds`: The X App access token.
        /// </summary>
        public Input<string>? OauthToken
        {
            get => _oauthToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _oauthToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("oauthTokenEndpointUrl")]
        private Input<string>? _oauthTokenEndpointUrl;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `ConfluentCloud`: OAuth 2.0 token endpoint URL used to obtain access tokens.
        /// </summary>
        public Input<string>? OauthTokenEndpointUrl
        {
            get => _oauthTokenEndpointUrl;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _oauthTokenEndpointUrl = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("oauthTokenSecret")]
        private Input<string>? _oauthTokenSecret;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Twitter`: The X App access token secret.
        /// 	- Service `TwitterAds`: The X App access token secret.
        /// </summary>
        public Input<string>? OauthTokenSecret
        {
            get => _oauthTokenSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _oauthTokenSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("ocapiAccessToken")]
        private Input<string>? _ocapiAccessToken;
        public Input<string>? OcapiAccessToken
        {
            get => _ocapiAccessToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _ocapiAccessToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("ocapiRefreshToken")]
        private Input<string>? _ocapiRefreshToken;
        public Input<string>? OcapiRefreshToken
        {
            get => _ocapiRefreshToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _ocapiRefreshToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Quickbooks`: `Realm ID` of your QuickBooks application.
        /// </summary>
        [Input("realmId")]
        public Input<string>? RealmId { get; set; }

        [Input("refreshToken")]
        private Input<string>? _refreshToken;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Adroll`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `Airtable`: The long-lived refresh token along with the client ID and client secret carry the information necessary to get a new access token for API resources.
        /// 	- Service `AmazonAds`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `AmazonDsp`: Your Amazon DSP refresh token.
        /// 	- Service `AmazonSellingPartner`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `Asana`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `AutodeskBim360`: Your Autodesk BIM 360 Refresh Token.
        /// 	- Service `AzureServiceBus`: The refresh token. Required if the authentication type is `AzureActiveDirectory`
        /// 	- Service `AzureSqlDb`: The long-lived Refresh token carries the information necessary to get a new access token for API resources.
        /// 	- Service `AzureSqlManagedDb`: The long-lived Refresh token carries the information necessary to get a new access token for API resources.
        /// 	- Service `BillingPlatform`: Your BillingPlatform refresh token.
        /// 	- Service `Bingads`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `BusinessCentral`: The long-lived refresh token along with the client ID and client secret parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `Calendly`: Your Calendly refresh token.
        /// 	- Service `Docebo`: Your Docebo Refresh Token.
        /// 	- Service `DoubleClickCampaignManager`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `DoubleClickPublishers`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `Drift`: Your Drift refresh token.
        /// 	- Service `Dropbox`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `Dynamics365`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `EmploymentHero`: Your Employment Hero refresh token.
        /// 	- Service `Freshbooks`: Your FreshBooks Refresh Token.
        /// 	- Service `Front`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `Gitlab`: Your GitLab refresh token.
        /// 	- Service `Gmail`: The long-lived `Refresh token` of your Gmail client application.
        /// 	- Service `GoogleAds`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `GoogleAnalytics4`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `GoogleBusinessProfile`: Your Google Business Profile Refresh token.
        /// 	- Service `GoogleCalendar`: Your Google Calendar refresh token.
        /// 	- Service `GoogleClassroom`: The long-lived `Refresh token` of your Google Calendar client application.
        /// 	- Service `GoogleDisplayAndVideo360`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `GooglePlay`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `GoogleSearchAds360`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `GoogleSheets`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `GoogleTagManager`: Your Google Tag Manager refresh token.
        /// 	- Service `GoogleTasks`: The long-lived refresh token of your Google Tasks client application.
        /// 	- Service `Helpscout`: The long-lived `refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `Hubspot`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `LightspeedRetailXseries`: Your Lightspeed Retail X-Series refresh token.
        /// 	- Service `LinkedinAds`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `LinkedinCompanyPages`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `MicrosoftLists`: The long-lived Refresh token carries the information necessary to get a new access token for API resources.
        /// 	- Service `OneDrive`: The long-lived `Refresh token` carries the information necessary to get a new access token for API resources.
        /// 	- Service `Optimizely`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `Outreach`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `PinterestAds`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `PinterestOrganic`: Your Pinterest refresh token.
        /// 	- Service `Pipedrive`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `Qualtrics`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `Quickbooks`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `Ramp`: Your Ramp refresh token.
        /// 	- Service `RedditAds`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `Salesforce`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `SalesforceSandbox`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `Salesloft`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `SharePoint`: The long-lived Refresh token carries the information necessary to get a new access token for API resources.
        /// 	- Service `SnapchatAds`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `SpotifyAds`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `TiktokOrganicApp`: Your TikTok Organic refresh token.
        /// 	- Service `Tremendous`: Your Tremendous refresh token.
        /// 	- Service `Typeform`: The Typeform API refresh token.
        /// 	- Service `Workday`: OAuth Refresh Token
        /// 	- Service `YahooSearchAdsYahooJapan`: Your Yahoo Search Ads Refresh Token.
        /// 	- Service `YoutubeAnalytics`: The long-lived `Refresh token` along with the `ClientId` and `ClientSecret` parameters carry the information necessary to get a new access token for API resources.
        /// 	- Service `ZohoCrm`: The long-lived `Refresh token`, along with the `ClientId` and `ClientSecret` parameters, carries the information necessary to get a new access token for API resources.
        /// 	- Service `Zoom`: Your Zoom Refresh token.
        /// </summary>
        public Input<string>? RefreshToken
        {
            get => _refreshToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _refreshToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("servicePrincipalClientCertPvtKey")]
        private Input<string>? _servicePrincipalClientCertPvtKey;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AzureSqlDb`: Contents of Service Principal Client Certificate Private Key.
        /// 	- Service `AzureSqlManagedDb`: Contents of Service Principal Client Certificate Private Key.
        /// </summary>
        public Input<string>? ServicePrincipalClientCertPvtKey
        {
            get => _servicePrincipalClientCertPvtKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _servicePrincipalClientCertPvtKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("servicePrincipalClientCertificate")]
        private Input<string>? _servicePrincipalClientCertificate;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AzureSqlDb`: Contents of Service Principal Client Certificate.
        /// 	- Service `AzureSqlManagedDb`: Contents of Service Principal Client Certificate.
        /// </summary>
        public Input<string>? ServicePrincipalClientCertificate
        {
            get => _servicePrincipalClientCertificate;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _servicePrincipalClientCertificate = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("servicePrincipalClientSecret")]
        private Input<string>? _servicePrincipalClientSecret;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AzureSqlDb`: Service Principal Client Secret.
        /// 	- Service `AzureSqlManagedDb`: Service Principal Client Secret.
        /// </summary>
        public Input<string>? ServicePrincipalClientSecret
        {
            get => _servicePrincipalClientSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _servicePrincipalClientSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AzureSqlDb`: Service Principal Client ID.
        /// 	- Service `AzureSqlManagedDb`: Service Principal Client ID.
        /// </summary>
        [Input("servicePrincipalId")]
        public Input<string>? ServicePrincipalId { get; set; }

        [Input("svcAccSecretKey")]
        private Input<string>? _svcAccSecretKey;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GooglePlay`: Service account secret key
        /// </summary>
        public Input<string>? SvcAccSecretKey
        {
            get => _svcAccSecretKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _svcAccSecretKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("systemUserAccessToken")]
        private Input<string>? _systemUserAccessToken;
        public Input<string>? SystemUserAccessToken
        {
            get => _systemUserAccessToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _systemUserAccessToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AppleSearchAds`: Apple Search Ads REST API Team ID. Must be populated if `IsAuth2Enabled` is set to `True`.
        /// </summary>
        [Input("teamId")]
        public Input<string>? TeamId { get; set; }

        [Input("tenantId")]
        private Input<string>? _tenantId;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AzureBlobStorage`: `Tenant ID` of your Microsoft client application.
        /// 	- Service `MicrosoftDynamics365Fno`: `Tenant ID` of your Microsoft client application.
        /// 	- Service `MicrosoftLists`: `Tenant ID` of your Microsoft client application.
        /// 	- Service `SharePoint`: `Tenant ID` of your Microsoft client application.
        /// </summary>
        public Input<string>? TenantId
        {
            get => _tenantId;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _tenantId = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("userAccessToken")]
        private Input<string>? _userAccessToken;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `FacebookAds`: System User Token. Use in combination with `ClientId` and `ClientSecret`. Use either `UserAccessToken` (for system token) or `AccessToken` (for user access token), not both at the same time.
        /// </summary>
        public Input<string>? UserAccessToken
        {
            get => _userAccessToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _userAccessToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("windowsAuthClientPrivateKey")]
        private Input<string>? _windowsAuthClientPrivateKey;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `SqlServer`: Private key associated with the Fivetran client certificate.
        /// </summary>
        public Input<string>? WindowsAuthClientPrivateKey
        {
            get => _windowsAuthClientPrivateKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _windowsAuthClientPrivateKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public ConnectorAuthArgs()
        {
        }
        public static new ConnectorAuthArgs Empty => new ConnectorAuthArgs();
    }
}
