// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Inputs
{

    public sealed class ConnectorConfigReportLevelGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: Flag to indicate if descendants are included or not.
        /// </summary>
        [Input("flag")]
        public Input<bool>? Flag { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: Level ID to sync.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: Flag to indicate if descendants are included or not
        /// </summary>
        [Input("includeDescendants")]
        public Input<bool>? IncludeDescendants { get; set; }

        public ConnectorConfigReportLevelGetArgs()
        {
        }
        public static new ConnectorConfigReportLevelGetArgs Empty => new ConnectorConfigReportLevelGetArgs();
    }
}
