// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Inputs
{

    public sealed class ConnectorAuthClientAccessArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Adroll`: `Client ID` of your AdRoll client application.
        /// 	- Service `Airtable`: `Client ID` of your Airtable client application.
        /// 	- Service `AmazonAds`: `Client ID` of your Amazon Ads client application.
        /// 	- Service `Asana`: `Client ID` of your Asana client application.
        /// 	- Service `AzureServiceBus`: `Client ID` of your Azure application. Required if the authentication type is `AzureActiveDirectory`
        /// 	- Service `Bingads`: `Client ID` of your Microsoft Advertising client application.
        /// 	- Service `BusinessCentral`: `Client ID` of your Airtable client application.
        /// 	- Service `DoubleClickCampaignManager`: `Client ID` of your Google Campaign Manager 360 client application.
        /// 	- Service `DoubleClickPublishers`: `Client ID` of your Google Ad Manager client application.
        /// 	- Service `Dropbox`: `Client ID` of your Dropbox client application.
        /// 	- Service `Dynamics365`: `Client ID` of your Dynamic 365 client application, or Service Principal.
        /// 	- Service `FacebookAds`: `Client ID` of your Facebook client application.
        /// 	- Service `FacebookPages`: `Client ID` of your Facebook  client application.
        /// 	- Service `FinancialForce`: `Client ID` of your Salesforce client application.
        /// 	- Service `Front`: `Client ID` of your Front client application.
        /// 	- Service `GoogleAds`: `Client ID` of your Google Ads client application.
        /// 	- Service `GoogleAnalytics`: `Client ID` of your Google Analytics client application.
        /// 	- Service `GoogleAnalytics4`: `Client ID` of your Google Analytics client application.
        /// 	- Service `GoogleAnalyticsMcf`: `Client ID` of your Google Analytics client application.
        /// 	- Service `GoogleDisplayAndVideo360`: `Client ID` of your Google Display &amp; Video 360 client application.
        /// 	- Service `GooglePlay`: `Client ID` of your Google Play client application.
        /// 	- Service `GoogleSearchAds360`: `Client ID` of your Google Search Ads 360 client application.
        /// 	- Service `GoogleSearchConsole`: `Client ID` of your Google Search Console client application.
        /// 	- Service `GoogleSheets`: `Client ID` of your Google Sheets client application.
        /// 	- Service `Helpscout`: `Client ID` of your Help Scout client application.
        /// 	- Service `Hubspot`: `Client ID` of your HubSpot client application.
        /// 	- Service `InstagramBusiness`: `Client ID` of your Facebook  client application.
        /// 	- Service `LinkedinAds`: `Client ID` of your LinkedIn client application.
        /// 	- Service `LinkedinCompanyPages`: `Client ID` of your LinkedIn client application.
        /// 	- Service `MicrosoftLists`: `Client ID` of your Microsoft client application.
        /// 	- Service `OneDrive`: `Client ID` of your Microsoft OneDrive client application.
        /// 	- Service `Optimizely`: `Client ID` of your Optimizely client application.
        /// 	- Service `Outreach`: `Client ID` of your Outreach client application.
        /// 	- Service `Pardot`: `Client ID` of your Pardot client application.
        /// 	- Service `PinterestAds`: `Client ID` of your Pinterest client application.
        /// 	- Service `Pipedrive`: `Client ID` of your Pipedrive client application.
        /// 	- Service `Qualtrics`: `Client ID` of your Qualtrics client application.
        /// 	- Service `Quickbooks`: `Client ID` of your QuickBooks client application.
        /// 	- Service `RedditAds`: `Client ID` of your Reddit Ads client application.
        /// 	- Service `Salesforce`: `Client ID` of your Salesforce client application.
        /// 	- Service `SalesforceSandbox`: `Client ID` of your Salesforce client application.
        /// 	- Service `SharePoint`: `Client ID` of your Microsoft client application.
        /// 	- Service `SnapchatAds`: `Client ID` of your Snapchat Ads client application.
        /// 	- Service `SpotifyAds`: `Client ID` of your Ad Studio application.
        /// 	- Service `SurveyMonkey`: `Client ID` of your SurveyMonkey client application.
        /// 	- Service `TiktokAds`: `Client ID` of your TikTok Ads client application.
        /// 	- Service `Twitter`: `Client ID` of your Twitter client application.
        /// 	- Service `TwitterAds`: `Client ID` of your Twitter Ads client application.
        /// 	- Service `Typeform`: The Typeform client ID.
        /// 	- Service `YahooGemini`: `Client ID` of your Yahoo Gemini client application.
        /// 	- Service `YoutubeAnalytics`: `Client ID` of your Youtube client application.
        /// 	- Service `ZohoCrm`: `Client ID` of your Zoho client application.
        /// </summary>
        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        [Input("clientSecret")]
        private Input<string>? _clientSecret;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Adroll`: `Client Secret` of your AdRoll client application.
        /// 	- Service `Airtable`: `Client Secret` of your Airtable client application.
        /// 	- Service `AmazonAds`: `Client Secret` of your Amazon Ads client application.
        /// 	- Service `Asana`: `Client Secret` of your Asana client application.
        /// 	- Service `AzureServiceBus`: `Client Secret` of your Azure application. Required if the authentication type is `AzureActiveDirectory`
        /// 	- Service `Bingads`: `Client Secret` of your Microsoft Advertising client application.
        /// 	- Service `BusinessCentral`: `Client Secret` of your Airtable client application.
        /// 	- Service `DoubleClickCampaignManager`: `Client Secret` of your Google Campaign Manager 360 client application.
        /// 	- Service `DoubleClickPublishers`: `Client Secret` of your Google Ad Manager client application.
        /// 	- Service `Dropbox`: `Client Secret` of your Dropbox client application.
        /// 	- Service `Dynamics365`: `Client Secret` of your Dynamic 365 client application, or Service Principal.
        /// 	- Service `FacebookAds`: `Client Secret` of your Facebook client application.
        /// 	- Service `FacebookPages`: `Client Secret` of your Facebook client application.
        /// 	- Service `FinancialForce`: `Client Secret` of your Salesforce client application.
        /// 	- Service `Front`: `Client Secret` of your Front client application.
        /// 	- Service `GoogleAds`: `Client Secret` of your Google Ads client application.
        /// 	- Service `GoogleAnalytics`: `Client Secret` of your Google Analytics client application.
        /// 	- Service `GoogleAnalytics4`: `Client Secret` of your Google Analytics client application.
        /// 	- Service `GoogleAnalyticsMcf`: `Client Secret` of your Google Analytics client application.
        /// 	- Service `GoogleDisplayAndVideo360`: `Client Secret` of your Google Display &amp; Video 360 client application.
        /// 	- Service `GooglePlay`: `Client Secret` of your Google Play client application.
        /// 	- Service `GoogleSearchAds360`: `Client Secret` of your Google Search Ads 360 client application.
        /// 	- Service `GoogleSearchConsole`: `Client Secret` of your Google Search Console client application.
        /// 	- Service `GoogleSheets`: `Client Secret` of your Google Sheets client application.
        /// 	- Service `Helpscout`: `Client Secret` of your Help Scout client application.
        /// 	- Service `Hubspot`: `Client Secret` of your HubSpot client application.
        /// 	- Service `InstagramBusiness`: `Client Secret` of your Facebook client application.
        /// 	- Service `LinkedinAds`: `Client Secret` of your LinkedIn client application.
        /// 	- Service `LinkedinCompanyPages`: `Client Secret` of your LinkedIn client application.
        /// 	- Service `MicrosoftLists`: `Client Secret` of your Microsoft client application.
        /// 	- Service `OneDrive`: `Client Secret` of your Microsoft OneDrive client application.
        /// 	- Service `Optimizely`: `Client Secret` of your Optimizely client application.
        /// 	- Service `Outreach`: `Client Secret` of your Outreach client application.
        /// 	- Service `Pardot`: `Client Secret` of your Pardot client application.
        /// 	- Service `PinterestAds`: `Client Secret` of your Pinterest client application.
        /// 	- Service `Pipedrive`: `Client Secret` of your Pipedrive client application.
        /// 	- Service `Qualtrics`: `Client Secret` of your Qualtrics client application.
        /// 	- Service `Quickbooks`: `Client Secret` of your QuickBooks client application.
        /// 	- Service `RedditAds`: `Client Secret` of your Reddit Ads client application.
        /// 	- Service `Salesforce`: `Client Secret` of your Salesforce client application.
        /// 	- Service `SalesforceSandbox`: `Client Secret` of your Salesforce client application.
        /// 	- Service `SharePoint`: `Client Secret` of your Microsoft client application.
        /// 	- Service `SnapchatAds`: `Client Secret` of your Snapchat Ads client application.
        /// 	- Service `SpotifyAds`: `Client Secret` of your Ad Studio application.
        /// 	- Service `SurveyMonkey`: `Client Secret` of your SurveyMonkey client application.
        /// 	- Service `TiktokAds`: `Client Secret` of your TikTok Ads client application.
        /// 	- Service `Twitter`: `Client Secret` of your Twitter client application.
        /// 	- Service `TwitterAds`: `Client Secret` of your Twitter Ads client application.
        /// 	- Service `Typeform`: The Typeform client secret.
        /// 	- Service `YahooGemini`: `Client Secret` of your Yahoo Gemini client application.
        /// 	- Service `YoutubeAnalytics`: `Client Secret` of your Youtube client application.
        /// 	- Service `ZohoCrm`: `Client Secret` of your Zoho client application.
        /// </summary>
        public Input<string>? ClientSecret
        {
            get => _clientSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAds`: Your approved `Developer token` to connect to the Google Ads API.
        /// </summary>
        [Input("developerToken")]
        public Input<string>? DeveloperToken { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAds`: Your company's name in your Google Ads client application.
        /// </summary>
        [Input("userAgent")]
        public Input<string>? UserAgent { get; set; }

        public ConnectorAuthClientAccessArgs()
        {
        }
        public static new ConnectorAuthClientAccessArgs Empty => new ConnectorAuthClientAccessArgs();
    }
}
