// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Inputs
{

    public sealed class ConnectionV2ScheduleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The cron expression for scheduled syncs (used when ScheduleType is CRON).
        /// </summary>
        [Input("cron")]
        public Input<string>? Cron { get; set; }

        [Input("daysOfWeeks")]
        private InputList<string>? _daysOfWeeks;

        /// <summary>
        /// The days of the week for scheduled syncs (used when ScheduleType is WEEKLY).
        /// </summary>
        public InputList<string> DaysOfWeeks
        {
            get => _daysOfWeeks ?? (_daysOfWeeks = new InputList<string>());
            set => _daysOfWeeks = value;
        }

        /// <summary>
        /// The interval in minutes between syncs (used when ScheduleType is INTERVAL).
        /// </summary>
        [Input("interval")]
        public Input<int>? Interval { get; set; }

        /// <summary>
        /// The connection schedule configuration type. Supported values: `Auto`, `Manual`.
        /// </summary>
        [Input("scheduleType")]
        public Input<string>? ScheduleType { get; set; }

        /// <summary>
        /// The time of day for scheduled syncs (format: HH:MM).
        /// </summary>
        [Input("timeOfDay")]
        public Input<string>? TimeOfDay { get; set; }

        public ConnectionV2ScheduleArgs()
        {
        }
        public static new ConnectionV2ScheduleArgs Empty => new ConnectionV2ScheduleArgs();
    }
}
