// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Inputs
{

    public sealed class GetConnectorConfigReportFilterInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("dimension", required: true)]
        public Input<string> Dimension { get; set; } = null!;

        [Input("expression", required: true)]
        public Input<string> Expression { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: The dimension name to filter on.
        /// </summary>
        [Input("filterDimension", required: true)]
        public Input<string> FilterDimension { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: Filter type for reports request. Possible values are INCLUDE and EXCLUDE
        /// </summary>
        [Input("filterType", required: true)]
        public Input<string> FilterType { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: The filter value.
        /// </summary>
        [Input("filterValue", required: true)]
        public Input<string> FilterValue { get; set; } = null!;

        [Input("filterValues", required: true)]
        private InputList<string>? _filterValues;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: The filter values for EXACT match type.
        /// </summary>
        public InputList<string> FilterValues
        {
            get => _filterValues ?? (_filterValues = new InputList<string>());
            set => _filterValues = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: The filter match type.
        /// </summary>
        [Input("matchType", required: true)]
        public Input<string> MatchType { get; set; } = null!;

        public GetConnectorConfigReportFilterInputArgs()
        {
        }
        public static new GetConnectorConfigReportFilterInputArgs Empty => new GetConnectorConfigReportFilterInputArgs();
    }
}
