// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Inputs
{

    public sealed class GetConnectorConfigAdobeAnalyticsConfigurationArgs : global::Pulumi.InvokeArgs
    {
        [Input("calculatedMetrics", required: true)]
        private List<string>? _calculatedMetrics;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AdobeAnalytics`: The CalculatedMetrics that you want to sync.
        /// </summary>
        public List<string> CalculatedMetrics
        {
            get => _calculatedMetrics ?? (_calculatedMetrics = new List<string>());
            set => _calculatedMetrics = value;
        }

        [Input("elements", required: true)]
        private List<string>? _elements;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AdobeAnalytics`: The elements that you want to sync.
        /// </summary>
        public List<string> Elements
        {
            get => _elements ?? (_elements = new List<string>());
            set => _elements = value;
        }

        [Input("metrics", required: true)]
        private List<string>? _metrics;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AdobeAnalytics`: The metrics that you want to sync.
        /// </summary>
        public List<string> Metrics
        {
            get => _metrics ?? (_metrics = new List<string>());
            set => _metrics = value;
        }

        [Input("reportSuites", required: true)]
        private List<string>? _reportSuites;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AdobeAnalytics`: Specific report suites to sync. Must be populated if `SyncMode` is set to `SpecificReportSuites`.
        /// </summary>
        public List<string> ReportSuites
        {
            get => _reportSuites ?? (_reportSuites = new List<string>());
            set => _reportSuites = value;
        }

        [Input("segments", required: true)]
        private List<string>? _segments;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AdobeAnalytics`: The segments that you want to sync.
        /// </summary>
        public List<string> Segments
        {
            get => _segments ?? (_segments = new List<string>());
            set => _segments = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AdobeAnalytics`: Whether to sync all report suites or specific report suites. Default value: `AllReportSuites` .
        /// </summary>
        [Input("syncMode", required: true)]
        public string SyncMode { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `AdobeAnalytics`: The table name unique within the schema to which connector will sync the data. Required for connector creation.
        /// </summary>
        [Input("table", required: true)]
        public string Table { get; set; } = null!;

        public GetConnectorConfigAdobeAnalyticsConfigurationArgs()
        {
        }
        public static new GetConnectorConfigAdobeAnalyticsConfigurationArgs Empty => new GetConnectorConfigAdobeAnalyticsConfigurationArgs();
    }
}
