// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Inputs
{

    public sealed class GetConnectorConfigReportArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: Account sync mode for the table. Options: `SYNC_ALL_ACCOUNTS` (sync all accounts) or `SELECT_SPECIFIC_ACCOUNTS` (sync selected accounts only).
        /// </summary>
        [Input("accountSyncMode", required: true)]
        public string AccountSyncMode { get; set; } = null!;

        [Input("accounts", required: true)]
        private List<Inputs.GetConnectorConfigReportAccountArgs>? _accounts;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: List of accounts to sync for the table, if applicable.
        /// </summary>
        public List<Inputs.GetConnectorConfigReportAccountArgs> Accounts
        {
            get => _accounts ?? (_accounts = new List<Inputs.GetConnectorConfigReportAccountArgs>());
            set => _accounts = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickPublishers`: Ad unit view for the report.
        /// </summary>
        [Input("adUnitView", required: true)]
        public string AdUnitView { get; set; } = null!;

        [Input("advertisers", required: true)]
        private List<string>? _advertisers;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleDisplayAndVideo360`: The list of advertisers to include into a sync. This parameter only takes effect when `ConfigMethod` is set to `CREATE_NEW`.
        /// </summary>
        public List<string> Advertisers
        {
            get => _advertisers ?? (_advertisers = new List<string>());
            set => _advertisers = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleSearchConsole`: (Optional) Aggregation type. Supported only for the `SEARCH_RESULTS` report type
        /// </summary>
        [Input("aggregation", required: true)]
        public string Aggregation { get; set; } = null!;

        [Input("attributes", required: true)]
        private List<string>? _attributes;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleSearchAds360`: The report attributes included to sync. Labeled `Fields` in the Fivetran dashboard.
        /// </summary>
        public List<string> Attributes
        {
            get => _attributes ?? (_attributes = new List<string>());
            set => _attributes = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Klaviyo`: Optional breakdown for Form Series reports. Select Form version ID to group data by individual form versions, or Form ID to group data by form only.
        /// </summary>
        [Input("breakdown", required: true)]
        public string Breakdown { get; set; } = null!;

        [Input("columns", required: true)]
        private List<string>? _columns;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickPublishers`: Columns provide all trafficking statistics and revenue information available for the chosen dimensions.
        /// </summary>
        public List<string> Columns
        {
            get => _columns ?? (_columns = new List<string>());
            set => _columns = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleDisplayAndVideo360`: The report configuration method. Specifies whether a new configuration is defined manually or an existing configuration is reused. The default value is `CREATE_NEW`.
        /// </summary>
        [Input("configMethod", required: true)]
        public string ConfigMethod { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics`: Whether to use the [Prebuilt Reports or Custom Reports](https://fivetran.com/docs/connectors/applications/google-analytics#schemainformation).
        /// 	- Service `GoogleAnalytics4`: Whether to use the Prebuilt Reports or Custom Reports.
        /// </summary>
        [Input("configType", required: true)]
        public string ConfigType { get; set; } = null!;

        [Input("conversionDimensions", required: true)]
        private List<string>? _conversionDimensions;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickCampaignManager`: Conversion Dimensions.
        /// </summary>
        public List<string> ConversionDimensions
        {
            get => _conversionDimensions ?? (_conversionDimensions = new List<string>());
            set => _conversionDimensions = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Klaviyo`: The ID of the conversion metric.
        /// </summary>
        [Input("conversionMetricId", required: true)]
        public string ConversionMetricId { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: List of currencies to sync for the table, if applicable.
        /// </summary>
        [Input("currency", required: true)]
        public string Currency { get; set; } = null!;

        [Input("customColumnIds", required: true)]
        private List<string>? _customColumnIds;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleSearchAds360`: The report custom column IDs included to sync.
        /// </summary>
        public List<string> CustomColumnIds
        {
            get => _customColumnIds ?? (_customColumnIds = new List<string>());
            set => _customColumnIds = value;
        }

        [Input("customDimensionKeyIds", required: true)]
        private List<string>? _customDimensionKeyIds;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickPublishers`: The list of custom dimension key IDs included in the report. Custom dimension keys can only be selected with the CUSTOM_DIMENSION dimension.
        /// </summary>
        public List<string> CustomDimensionKeyIds
        {
            get => _customDimensionKeyIds ?? (_customDimensionKeyIds = new List<string>());
            set => _customDimensionKeyIds = value;
        }

        [Input("customFieldIds", required: true)]
        private List<string>? _customFieldIds;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickPublishers`: The list of custom field IDs included in the report. Custom fields can only be selected with their corresponding dimensions.
        /// </summary>
        public List<string> CustomFieldIds
        {
            get => _customFieldIds ?? (_customFieldIds = new List<string>());
            set => _customFieldIds = value;
        }

        [Input("customFloodlightVariables", required: true)]
        private List<string>? _customFloodlightVariables;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickCampaignManager`: Custom Floodlight variables enable you to capture information beyond the basics (visits and revenue) that you can collect with standard parameters in your tags.
        /// </summary>
        public List<string> CustomFloodlightVariables
        {
            get => _customFloodlightVariables ?? (_customFloodlightVariables = new List<string>());
            set => _customFloodlightVariables = value;
        }

        [Input("dimensionAttributes", required: true)]
        private List<string>? _dimensionAttributes;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickPublishers`: Dimension attributes provide additional fields associated with a dimension. Dimension attributes can only be selected with their corresponding dimensions.
        /// </summary>
        public List<string> DimensionAttributes
        {
            get => _dimensionAttributes ?? (_dimensionAttributes = new List<string>());
            set => _dimensionAttributes = value;
        }

        [Input("dimensions", required: true)]
        private List<string>? _dimensions;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickCampaignManager`: Report dimensions to include in a sync. The `Date` dimension is mandatory for all report types. The `Advertiser` dimension is mandatory for the `REACH` report type
        /// 	- Service `DoubleClickPublishers`: Report dimensions to include in the sync. The `Date` dimension is mandatory for all the report types.
        /// 	- Service `GoogleAnalytics`: The report dimensions to include into a sync. The `Date` dimension is mandatory for all the report types.
        /// 	- Service `GoogleAnalytics4`: The report dimensions to include into a sync.
        /// 	- Service `GoogleDisplayAndVideo360`: The report dimensions (filters) to include into a sync. The dimension names are provided in the API format. This is a required parameter when `ConfigMethod` is set to `CREATE_NEW`.
        /// 	- Service `GoogleSearchConsole`: The report dimensions included to sync.
        /// 	- Service `WorkdayAdaptive`: List of dimensions to sync for the table, if applicable.
        /// </summary>
        public List<string> Dimensions
        {
            get => _dimensions ?? (_dimensions = new List<string>());
            set => _dimensions = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Workday`: Dynamic parameter field name
        /// </summary>
        [Input("dynamicParameterField", required: true)]
        public string DynamicParameterField { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickCampaignManager`: Specifies whether to enable all reach dimension combinations in the report. Default value: `False`
        /// </summary>
        [Input("enableAllDimensionCombinations", required: true)]
        public bool EnableAllDimensionCombinations { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Workday`: Select this option to enable dynamic report parameters.
        /// </summary>
        [Input("enableDynamicParameters", required: true)]
        public bool EnableDynamicParameters { get; set; }

        [Input("fields", required: true)]
        private List<string>? _fields;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAds`: A list of the fields to sync. Must be populated if `ConfigType` is set to `Custom`.
        /// </summary>
        public List<string> Fields
        {
            get => _fields ?? (_fields = new List<string>());
            set => _fields = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics`: String parameter restricts the data returned for your report. To use the filter parameter, specify a dimension or metric on which to filter, followed by the filter expression
        /// </summary>
        [Input("filter", required: true)]
        public string Filter { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: The dimension name to filter on.
        /// </summary>
        [Input("filterFieldName", required: true)]
        public string FilterFieldName { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: Filter type for reports request. Possible values are INCLUDE and EXCLUDE
        /// </summary>
        [Input("filterType", required: true)]
        public string FilterType { get; set; } = null!;

        [Input("filterValue", required: true)]
        public string FilterValue { get; set; } = null!;

        [Input("filters", required: true)]
        private List<Inputs.GetConnectorConfigReportFilterArgs>? _filters;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: The list of filters to apply to the report data.
        /// 	- Service `GoogleSearchConsole`: The list of filters to be applied to the report.
        /// </summary>
        public List<Inputs.GetConnectorConfigReportFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetConnectorConfigReportFilterArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Workday`: Select this option to generate a Primary Key for reports where no single column or combination of columns can be used to form a Primary Key.
        /// </summary>
        [Input("generateFivetranPk", required: true)]
        public bool GenerateFivetranPk { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: Include zero rows in the table sync.
        /// </summary>
        [Input("includeZeroRows", required: true)]
        public bool IncludeZeroRows { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Klaviyo`: The interval used in the API calls to retrieve the reports.
        /// </summary>
        [Input("interval", required: true)]
        public string Interval { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: Level sync mode for the table. Options: `SYNC_ALL_LEVELS` (sync all levels) or `SELECT_SPECIFIC_LEVELS` (sync selected levels only).
        /// </summary>
        [Input("levelSyncMode", required: true)]
        public string LevelSyncMode { get; set; } = null!;

        [Input("levels", required: true)]
        private List<Inputs.GetConnectorConfigReportLevelArgs>? _levels;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: List of levels to sync for the table, if applicable.
        /// </summary>
        public List<Inputs.GetConnectorConfigReportLevelArgs> Levels
        {
            get => _levels ?? (_levels = new List<Inputs.GetConnectorConfigReportLevelArgs>());
            set => _levels = value;
        }

        [Input("metrics", required: true)]
        private List<string>? _metrics;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickCampaignManager`: Report metrics to include into a sync.
        /// 	- Service `GoogleAnalytics`: The report metrics to include into a sync.
        /// 	- Service `GoogleAnalytics4`: The report metrics to include into a sync.
        /// 	- Service `GoogleDisplayAndVideo360`: The report metrics to include into a sync. The metric names are provided in the API format. This is a required parameter when `ConfigMethod` is set to `CREATE_NEW`.
        /// 	- Service `GoogleSearchAds360`: The report metrics included to sync.
        /// </summary>
        public List<string> Metrics
        {
            get => _metrics ?? (_metrics = new List<string>());
            set => _metrics = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Klaviyo`: The name of the custom report. The same name is used to name the table in the destination.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("partners", required: true)]
        private List<string>? _partners;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleDisplayAndVideo360`: The list of partners to include into a sync. This parameter only takes effect when `ConfigMethod` is set to `CREATE_NEW`.
        /// </summary>
        public List<string> Partners
        {
            get => _partners ?? (_partners = new List<string>());
            set => _partners = value;
        }

        [Input("perInteractionDimensions", required: true)]
        private List<string>? _perInteractionDimensions;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickCampaignManager`: Per Interaction Dimensions.
        /// </summary>
        public List<string> PerInteractionDimensions
        {
            get => _perInteractionDimensions ?? (_perInteractionDimensions = new List<string>());
            set => _perInteractionDimensions = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics`: The name of the Prebuilt Report from which the connector will sync the data.
        /// 	- Service `GoogleAnalytics4`: The name of the Prebuilt Report from which the connector will sync the data.
        /// </summary>
        [Input("prebuiltReport", required: true)]
        public string PrebuiltReport { get; set; } = null!;

        [Input("primaryKeys", required: true)]
        private List<string>? _primaryKeys;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Workday`: Primary Keys
        /// </summary>
        public List<string> PrimaryKeys
        {
            get => _primaryKeys ?? (_primaryKeys = new List<string>());
            set => _primaryKeys = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleDisplayAndVideo360`: The ID of the query whose configuration you want to reuse. This is a required parameter when `ConfigMethod` is set to `REUSE_EXISTING`.
        /// </summary>
        [Input("queryId", required: true)]
        public string QueryId { get; set; } = null!;

        [Input("reportConfigurationIds", required: true)]
        private List<string>? _reportConfigurationIds;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickCampaignManager`: You can select only one Floodlight Configuration ID per account.
        /// </summary>
        public List<string> ReportConfigurationIds
        {
            get => _reportConfigurationIds ?? (_reportConfigurationIds = new List<string>());
            set => _reportConfigurationIds = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Workday`: This is to select report format from JSON and CSV. By default, report format is JSON.
        /// </summary>
        [Input("reportFormatType", required: true)]
        public string ReportFormatType { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickCampaignManager`: Type of reporting data to sync. Default value: `STANDARD`.
        /// 	- Service `GoogleAds`: The name of the Google Ads report from which the connector will sync the data. [Possible ReportType values](https://developers.google.com/adwords/api/docs/appendix/reports#report-types).
        /// 	- Service `GoogleDisplayAndVideo360`: The type of the report to create. This is a required parameter when `ConfigMethod` is set to `CREATE_NEW`.
        /// 	- Service `GoogleSearchAds360`: The type of report. Labeled `Resource type` in the Fivetran dashboard.
        /// 	- Service `GoogleSearchConsole`: The type of report
        /// </summary>
        [Input("reportType", required: true)]
        public string ReportType { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Workday`: URL for a live custom report.
        /// </summary>
        [Input("reportUrl", required: true)]
        public string ReportUrl { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickCampaignManager`: The custom window size for rollback syncs (between 1 and 90).
        /// 	- Service `GoogleAnalytics4`: The custom window size for rollback syncs.
        /// 	- Service `GoogleSearchAds360`: The custom window size for rollback syncs (between 2 and 90).
        /// </summary>
        [Input("rollbackWindow", required: true)]
        public int RollbackWindow { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Klaviyo`: The number of days to look back during each sync to capture late-arriving data. Valid range: 2 to 90 days. Default: 5 days.
        /// </summary>
        [Input("rollbackWindowInDays", required: true)]
        public int RollbackWindowInDays { get; set; }

        [Input("searchTypes", required: true)]
        private List<string>? _searchTypes;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleSearchConsole`: Search types included to sync. Supported only for the `SEARCH_RESULTS` report type
        /// </summary>
        public List<string> SearchTypes
        {
            get => _searchTypes ?? (_searchTypes = new List<string>());
            set => _searchTypes = value;
        }

        [Input("segmentIds", required: true)]
        private List<string>? _segmentIds;
        public List<string> SegmentIds
        {
            get => _segmentIds ?? (_segmentIds = new List<string>());
            set => _segmentIds = value;
        }

        [Input("segments", required: true)]
        private List<string>? _segments;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics`: A segment is a subset of your Analytics data that is made up of one or more non-destructive filters (filters that do not alter the underlying data). Those filters isolate subsets of users, sessions, and hits.
        /// 	- Service `GoogleSearchAds360`: The report segments included to sync.
        /// </summary>
        public List<string> Segments
        {
            get => _segments ?? (_segments = new List<string>());
            set => _segments = value;
        }

        [Input("selectedAccounts", required: true)]
        private List<string>? _selectedAccounts;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: List of account IDs to sync when `accountSyncMode` is `SELECT_SPECIFIC_ACCOUNTS`. Each ID should be in the format: `accountId,isAssumption` (e.g., `1,false`).
        /// </summary>
        public List<string> SelectedAccounts
        {
            get => _selectedAccounts ?? (_selectedAccounts = new List<string>());
            set => _selectedAccounts = value;
        }

        [Input("selectedLevels", required: true)]
        private List<string>? _selectedLevels;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: List of level IDs to sync when `levelSyncMode` is `SELECT_SPECIFIC_LEVELS`.
        /// </summary>
        public List<string> SelectedLevels
        {
            get => _selectedLevels ?? (_selectedLevels = new List<string>());
            set => _selectedLevels = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleDisplayAndVideo360`: If enabled, the report will be queried separately for each advertiser, and the FILTER_ADVERTISER dimension will be added automatically if not already selected. This parameter only takes effect when `ConfigMethod` is set to `CREATE_NEW`. The default value is `False`.
        /// </summary>
        [Input("splitByAdvertiser", required: true)]
        public bool SplitByAdvertiser { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Workday`: Start date
        /// </summary>
        [Input("startDate", required: true)]
        public string StartDate { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Workday`: Start date parameter field name
        /// </summary>
        [Input("startDateParameterField", required: true)]
        public string StartDateParameterField { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: Start month for the table sync, in MM format
        /// </summary>
        [Input("startMonth", required: true)]
        public string StartMonth { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: Start year for the table sync, in YYYY format
        /// </summary>
        [Input("startYear", required: true)]
        public string StartYear { get; set; } = null!;

        [Input("statistics", required: true)]
        private List<string>? _statistics;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Klaviyo`: The list of statistics to be retrieved.
        /// </summary>
        public List<string> Statistics
        {
            get => _statistics ?? (_statistics = new List<string>());
            set => _statistics = value;
        }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Workday`: This option is to unpack the nested columns and sync them separately. By default, we sync the nested columns as JSON objects.
        /// </summary>
        [Input("supportNestedColumns", required: true)]
        public bool SupportNestedColumns { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: Flag to indicate if descendant accounts should be included for the selected accounts.
        /// </summary>
        [Input("syncDescendantAccounts", required: true)]
        public bool SyncDescendantAccounts { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: Flag to indicate if descendant levels should be included for the selected levels.
        /// </summary>
        [Input("syncDescendantLevels", required: true)]
        public bool SyncDescendantLevels { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Workday`: Dynamic report parameters sync strategy
        /// </summary>
        [Input("syncStrategy", required: true)]
        public string SyncStrategy { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `DoubleClickCampaignManager`: Destination table name. It must be unique within this connection and must comply with Fivetran's naming conventions.
        /// 	- Service `DoubleClickPublishers`: The name of the table within the schema storing the data for a given report.
        /// 	- Service `GoogleAds`: The table name within the schema to which connector will sync the data of the specific report.
        /// 	- Service `GoogleAnalytics`: The table name within the schema to which connector will sync the data of the specific report.
        /// 	- Service `GoogleAnalytics4`: The table name within the schema to which connector will sync the data of the specific report.
        /// 	- Service `GoogleSearchAds360`: The name of a table within the schema to which connector syncs the data of a given report.
        /// 	- Service `GoogleSearchConsole`: The name of a table within the schema to which connector syncs the data of a given report.
        /// 	- Service `Workday`: The table name within the schema to which connector will sync the data of the specific report.
        /// 	- Service `WorkdayAdaptive`: Table name to be synced.
        /// </summary>
        [Input("table", required: true)]
        public string Table { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleDisplayAndVideo360`: The table name within the schema to which connector will sync the data of the specific report.
        /// </summary>
        [Input("tableName", required: true)]
        public string TableName { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleAnalytics4`: The report data aggregation time granularity.
        /// </summary>
        [Input("timeAggregationGranularity", required: true)]
        public string TimeAggregationGranularity { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `Klaviyo`: The type of the custom report.
        /// </summary>
        [Input("type", required: true)]
        public string Type { get; set; } = null!;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `GoogleDisplayAndVideo360`: Specifies whether the configuration is updated before each sync or only when the connector settings are saved. This parameter only takes effect when `ConfigMethod` is set to `REUSE_EXISTING`. The default value is `True`.
        /// </summary>
        [Input("updateConfigOnEachSync", required: true)]
        public bool UpdateConfigOnEachSync { get; set; }

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: Version sync strategy for the table, `SYNC_ALL_AND_NEW_VERSIONS` or `SYNC_SELECT_VERSIONS`.
        /// </summary>
        [Input("versionSyncStrategy", required: true)]
        public string VersionSyncStrategy { get; set; } = null!;

        [Input("versions", required: true)]
        private List<string>? _versions;

        /// <summary>
        /// Field usage depends on `Service` value: 
        /// 	- Service `WorkdayAdaptive`: List of versions to sync for the table, if versionSyncStrategy is `SYNC_SELECT_VERSIONS`.
        /// </summary>
        public List<string> Versions
        {
            get => _versions ?? (_versions = new List<string>());
            set => _versions = value;
        }

        public GetConnectorConfigReportArgs()
        {
        }
        public static new GetConnectorConfigReportArgs Empty => new GetConnectorConfigReportArgs();
    }
}
