// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Fivetran.Inputs
{

    public sealed class GetExternalLoggingConfigArgs : global::Pulumi.InvokeArgs
    {
        [Input("accessKeyId", required: true)]
        public string AccessKeyId { get; set; } = null!;

        [Input("accessKeySecret", required: true)]
        private string? _accessKeySecret;
        public string? AccessKeySecret
        {
            get => _accessKeySecret;
            set => _accessKeySecret = value;
        }

        [Input("apiKey", required: true)]
        private string? _apiKey;
        public string? ApiKey
        {
            get => _apiKey;
            set => _apiKey = value;
        }

        [Input("channel", required: true)]
        public string Channel { get; set; } = null!;

        [Input("enableSsl", required: true)]
        public bool EnableSsl { get; set; }

        [Input("externalId", required: true)]
        public string ExternalId { get; set; } = null!;

        [Input("host", required: true)]
        public string Host { get; set; } = null!;

        [Input("hostname", required: true)]
        public string Hostname { get; set; } = null!;

        [Input("logGroupName", required: true)]
        public string LogGroupName { get; set; } = null!;

        [Input("port", required: true)]
        public int Port { get; set; }

        [Input("primaryKey", required: true)]
        private string? _primaryKey;
        public string? PrimaryKey
        {
            get => _primaryKey;
            set => _primaryKey = value;
        }

        [Input("projectId", required: true)]
        public string ProjectId { get; set; } = null!;

        [Input("region", required: true)]
        public string Region { get; set; } = null!;

        [Input("roleArn", required: true)]
        public string RoleArn { get; set; } = null!;

        [Input("serviceAccountKey", required: true)]
        public string ServiceAccountKey { get; set; } = null!;

        [Input("subDomain", required: true)]
        public string SubDomain { get; set; } = null!;

        [Input("token", required: true)]
        private string? _token;
        public string? Token
        {
            get => _token;
            set => _token = value;
        }

        [Input("workspaceId", required: true)]
        public string WorkspaceId { get; set; } = null!;

        public GetExternalLoggingConfigArgs()
        {
        }
        public static new GetExternalLoggingConfigArgs Empty => new GetExternalLoggingConfigArgs();
    }
}
